Handle color outside post content
Automattic/newspack-theme pull request #1131
Opened 2020-10-30 13:16 UTC by adekbadek

### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

https://github.com/Automattic/newspack-popups/pull/292 introduces an "Above site header" placement option. 

Note: this approach might be too heavy-handed, so I'd defer to @laurelfulford to see what can these brake ⚠️

### How to test the changes in this Pull Request:

1. Follow testing steps in https://github.com/Automattic/newspack-popups/pull/292
2. On `master`, observe the theme colors are not applied to blocks used in an "above header" campaign
3. Switch to this PR, observe that the theme colors are applied

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2020-10-30 23:09 UTC, laurelfulford requested changes
Unfortunately, removing the `.entry .entry-content` classes from the custom colour code cause them to stop working in the content area :( This is largely because these the styles in the theme overall are needlessly complicated; I spent time early on trying to move blocks out of that selector, but they're kind of in a half-in-half-out status at the moment. 

I think there's a couple possible alternatives:

* For the short-term, just duplicate the color styles with the `.newspack-inline-popup` class instead of the `.entry .entry-content` class. Pros: requires very little testing, and has the least potential to be 'dangerous' for existing styles. Cons: adds a lot more CSS. 

Or:

* Go through the _blocks.scss and move all of the colour-related styles outside of the `.entry .entry-content` selector. It's not a full move away from that selector, but it should enable us to simplify the colour styles to apply everywhere. Pros: Doesn't add a lot of CSS bulk. Cons: will require more testing to make sure existing styles in the content aren't broken. 

I'm happy to take a swing at option two and see if it's as 'easy' an approach as I hope it will be. If timing is an issue, it might be best to go with option one for the short-term. 

Just let me know if you have any questions at all about this!

2020-11-02 10:10 UTC, adekbadek commented
It seems like the changes in `color-patters.php` were not needed after all – the theme colors are picked up with the change to `_blocks.scss` only.

2020-11-02 22:01 UTC, laurelfulford requested changes
Unfortunately, because the custom colour and text styles use the `.entry .entry-content`, they aren't applied to the campaigns.

Here is my terrible campaign in the editor, using purple and green as the site's custom colours, and Chalkboard and Impact for the site fonts:

![image](https://user-images.githubusercontent.com/177561/97921314-9c5d3080-1d0f-11eb-8cbe-0ec3e8fe1129.png)

When placed on the top, only the most general custom styles (paragraph and header) are applied; all colours, and some more specific fonts (like for buttons) are not:

![image](https://user-images.githubusercontent.com/177561/97921378-b991ff00-1d0f-11eb-8ab1-540853e79b73.png)

I think we might either need to do the 'nuclear' option (adding a bunch of classes), or, ideally, simplify these selectors in the theme a bit 😕 I can start on the latter; the issue is just that they're going to be time-consuming to test, but I think it'll be best in the long run.

2020-12-09 10:42 UTC, adekbadek commented
Closing in favour of https://github.com/Automattic/newspack-theme/pull/1133

2020-12-09 10:42 UTC, closed without merging