fix: correct issue with primary menu background control
Automattic/newspack-theme pull request #1167
Opened 2020-12-02 23:03 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes issue where primary colour background control wasn't showing when expected.

### How to test the changes in this Pull Request:

1. Apply the PR and run`npm run build`
2. Try Header Settings > Appearance > Solid Background - toggle on and off the Header Background Colour and the primary background colour option should appear with the regular header background option.
3. Disable Header Settings > Appearance > Solid Background  - primary background colour should be gone
4. Enable Header Settings > Appearance > Solid Background - it should be back 
5. Enable Header Settings > Appearance > Short Header - it should be gone
6. Try toggling on and off Colors > Header Background Colour and make sure the primary menu option stays hidden. 
7. Turn Colors > Header Background Colour off. 
8. Turn Header Settings > Appearance > Short Header off.
9. Turn Colors > Header Background Colour on -- the primary menu option should be back. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-12-02 23:24 UTC, dkoo requested changes
There are a lot of combinations here! I went through the steps and the only thing I saw that differed from what you specified was this:

> Enable Header Settings > Appearance > Short Header - it should be gone

With both "Solid Background" and "Short Header" options enabled in Header Settings > Appearance, the Header Background color option was still visible in Colors. This doesn't seem to be a problem to me, though, since it did change the short header color as expected.

2020-12-02 23:50 UTC, laurelfulford commented
> With both "Solid Background" and "Short Header" options enabled in Header Settings > Appearance, the Header Background color option was still visible in Colors.

We discussed a bit in Slack but just to close the loop here -- the menu background option should be the only one that's not visible in this case - the header background should still be there. Apologies for the confusing instructions for this very confusing control! 😬

2020-12-03 01:15 UTC, dkoo approved these changes
This explanation clears things up for me:

> It was the primary menu background that shouldn’t be there, not the header background itself — the primary menu background just shouldn’t display when it’s beside the logo, because it doesn’t have a different coloured background in that case.

Confirmed that this is the behavior. Looks good!

2020-12-03 01:18 UTC, laurelfulford commented
Thanks Derrick!

2020-12-03 01:18 UTC, merged