feat: add styles for the block 'read more' links
Automattic/newspack-theme pull request #1191
Opened 2020-12-19 01:14 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds some styles to the new 'Read More' link added to the Homepage Posts block. It needs to be tested with https://github.com/Automattic/newspack-blocks/pull/656 applied.

### How to test the changes in this Pull Request:

1. Set your test site to use the default font and colours.
2. Apply this PR to the theme, and https://github.com/Automattic/newspack-blocks/pull/656 to the Newspack Blocks, and run `npm run build` for each. 
3. Add some homepage posts blocks with the Read More link enabled. 
4. View on the front-end and in the editor; confirm that the link is the same colour as the text, lacks a text underline, and has an arrow. When the block type scale is 4 and higher, the link font size should be slightly smaller; for the type scale 1-3, the link should be the same font size:

![image](https://user-images.githubusercontent.com/177561/102676579-2d1e8d00-4153-11eb-9bba-9a622abf746b.png)

![image](https://user-images.githubusercontent.com/177561/102676594-360f5e80-4153-11eb-9c6e-1c0b1ed29929.png)

5. Try changing the block text colour and confirm that the link picks it up:

![image](https://user-images.githubusercontent.com/177561/102676609-3f003000-4153-11eb-8e49-7fec9c171aa9.png)

6. Try changing the site's custom colours and fonts; confirm they're picked up as expected (with the link picking up the body font, and still the same colour as the text):

![image](https://user-images.githubusercontent.com/177561/102676795-12004d00-4154-11eb-98f1-e8780ededd89.png)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-04 18:06 UTC, laurelfulford commented
Switching this PR to draft more to rework this a bit -- I think it's too opinionated, and after the benefit of some time away, the vertical spacing looks off. Should have an update shortly!

2021-01-05 18:18 UTC, dkoo requested changes
<img width="403" alt="Screen Shot 2021-01-05 at 11 14 53 AM" src="https://user-images.githubusercontent.com/2230142/103683461-73dbf780-4f47-11eb-8d84-f91295d2b3e4.png">

Code looks good to me, and I like the subtler style. My only question is, is it now *too* subtle? I find it hard to tell at a glance that these are links and not regular text since in many cases it looks identical to the excerpt when not in a hover state. If you think that's okay, I'll go ahead and approve, but it seems like a minor accessibility concern to me.

2021-01-05 19:09 UTC, laurelfulford commented
> My only question is, is it now too subtle?

😂 this honestly has been bugging me the entire break -- I don't disagree! 

Some other things I tried include:

* An arrow at the end, like "Keep Reading →", which I then started worrying was too "bloggy" or opinionated; you can also add an arrow to the actual text label of the button, so it seemed like "a lot" to put on all sites. 
* Making the link use a different font, but that made it seem to be part of the post meta rather than the excerpt (since it uses the header font -- it's less obvious with the settings on your test site, but when the body is serif and the headers is not, it feels... off). 
* Making it bolded, but that didn't totally read link-like, and competed visually with the post meta. 

I've pushed up an update that adds an underline in 990fc5e; I'd also be happy to re-try the arrow if that doesn't seem bad, or bolding? We're probably to be overriding this with Custom CSS on some sites no matter what, it's definitely better to make sure the default represents best practices!

I put together some screenshots to give better examples of what I'm talking about -- it's also very possible I'm overthinking these:

Underline (current):

![image](https://user-images.githubusercontent.com/177561/103687740-a1c03c80-4f45-11eb-9a44-b1b04828a4cd.png)

Arrows:

![image](https://user-images.githubusercontent.com/177561/103687847-c9170980-4f45-11eb-991d-dd4eee706a53.png)

Bold:

![image](https://user-images.githubusercontent.com/177561/103688017-0ed3d200-4f46-11eb-8320-e8eff36e943b.png)

Header font + bolding:

![image](https://user-images.githubusercontent.com/177561/103688219-58bcb800-4f46-11eb-905b-782ec41a88ae.png)

2021-01-05 20:00 UTC, dkoo approved these changes
Oh boy, sounds like you've already considered all this and more. I'll go ahead and approve and let you decide which approach you want to go with. The underline looks fine to me, FWIW. 😁

2021-01-05 22:37 UTC, laurelfulford commented
Thanks @dkoo! Haha there's no point thinking about something if you can't _over_ think it! 

I think the underline is a good in-between option -- link-y and noticeable compared to how it looked before, but not too much, and easy to override should specific publishers want to see changes (it's just picking up the default link styles, at this point).

2021-01-05 22:37 UTC, merged