Pullquote Block: Make sure italics are working
Automattic/newspack-theme pull request #1193
Opened 2021-01-06 01:30 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In the Newspack theme, the default, Sacha and Scott all italicize the pullquote block, so when you apply italics to part of the block, it switches it to non-italics instead.

However, Nelson, Katharine and Joseph do not italicize the pullquote by default, but the italicized styles aren't working. This PR fixes that.

Closes #1187

### How to test the changes in this Pull Request:

1. Start with the theme Newspack Katharine.
2. Create a Pullquote block and italicize part of it.
3. Note that your italics aren't being applied:

![image](https://user-images.githubusercontent.com/177561/103718494-b5869580-4f7b-11eb-84f1-5dfe39046013.png)

4. Apply the PR and run `npm run build`.
5. Confirm that your italics are now being applied in the editor and on the front-end:

![image](https://user-images.githubusercontent.com/177561/103718449-9ee03e80-4f7b-11eb-8953-713c6c589d91.png)

6. Check Newspack Nelson and Joseph, and confirm the italics working there, too. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-15 21:54 UTC, dkoo requested changes
Katharine and Nelson both look good in editor and front-end. Joseph's editor styles don't seem to match the front-end, however. I think it's because the containing `p` in Joseph doesn't have `font-style: normal` like the other child themes' editor styles.

Front-end:
<img width="792" alt="Screen Shot 2021-01-15 at 2 52 44 PM" src="https://user-images.githubusercontent.com/2230142/104782392-5970fd80-5741-11eb-9bea-5a760f0723b4.png">

Editor:
<img width="837" alt="Screen Shot 2021-01-15 at 2 52 40 PM" src="https://user-images.githubusercontent.com/2230142/104782406-5e35b180-5741-11eb-9e73-56327fc7da72.png">

2021-01-15 21:54 UTC, dkoo commented on newspack-joseph/sass/style-editor.scss
>  			}
Noting that the comment on line 2 of this file names the wrong child theme (Sacha—should say Joseph).

2021-01-15 23:20 UTC, laurelfulford commented on newspack-joseph/sass/style-editor.scss
>  			}
Oooh good catch! 😳 That's fixed in ffe68ff.

2021-01-15 23:20 UTC, laurelfulford commented
Thanks for catching that, Derrick! It should now be fixed; I've also rebased the latest theme updated into this PR to avoid merge conflicts.

2021-01-18 20:00 UTC, dkoo approved these changes
Much better!

<img width="823" alt="Screen Shot 2021-01-18 at 12 59 49 PM" src="https://user-images.githubusercontent.com/2230142/104958357-199e5600-598d-11eb-9397-9552fa5f991c.png">
<img width="799" alt="Screen Shot 2021-01-18 at 12 59 53 PM" src="https://user-images.githubusercontent.com/2230142/104958360-1a36ec80-598d-11eb-824e-bcc17605d8dc.png">

2021-01-19 16:08 UTC, laurelfulford commented
Thanks Derrick!

2021-01-19 16:08 UTC, merged