Add option to hide page title
Automattic/newspack-theme pull request #1200
Opened 2021-01-09 01:22 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds an option to hide the page title on individual pages on the front-end.

Closes #1048.

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`.
2. Edit a page; confirm that you have the option to hide the title under Status & Visibility, and that it's off by default.

![image](https://user-images.githubusercontent.com/177561/104078905-50c67780-51d5-11eb-82a6-4ea1025b1a0b.png)

3. Enable 'Hide page title', and click 'Update'.
4. Confirm that the page title is not displaying: 

![image](https://user-images.githubusercontent.com/177561/104079028-d64a2780-51d5-11eb-91a7-9d4afe4e875c.png)

5. Toggle the Hide page title option back on, and confirm that the title displays again. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-11 21:20 UTC, dkoo requested changes
I've got one performance improvement suggestion which I think is a good idea to implement, and one organizational suggestion which is more of a suggestion but not a blocker if you don't like it.

Also wanted to confirm, did you mean to intentionally leave the `h1` title element in the markup, but hidden with CSS for SEO purposes? Because we could also just not show the title at all in the markup if the "hide title" option is enabled.

2021-01-11 21:20 UTC, dkoo commented on newspack-theme/js/src/hide-page-title.js
> +'use strict';
**Not a blocker:** most of this code is repeated from `post-date-updated.js`, right? What if we were to combine both files and nest both toggle controls under `PluginPostStatusInfo`? This would let you enqueue the file in both posts and pages, and manage all the `PluginPostStatusInfo` extensions in one place (in the JS, you would need to use the `getCurrentPostType` selector and conditionally show the options you want for posts vs. pages based on that). 

Totally not necessary if you prefer to keep each option separate, though.

2021-01-20 01:29 UTC, laurelfulford commented on newspack-theme/functions.php
> +	if ( 'page' === get_current_screen()->post_type ) {
Thanks Derrick! I like this approach; I've updated this section in e42768e.

2021-01-20 01:30 UTC, laurelfulford commented on newspack-theme/js/src/hide-page-title.js
> +'use strict';
I've made this update in e18a52e (along with some CSS tweaks); it's quite possible I've made it more convoluted than necessary, so just let me know if it could use some adjustments! :)

2021-01-20 01:32 UTC, laurelfulford commented
Thanks Derrick! This should be ready for another look through.

> Also wanted to confirm, did you mean to intentionally leave the h1 title element in the markup, but hidden with CSS for SEO purposes? Because we could also just not show the title at all in the markup if the "hide title" option is enabled.

I honestly wasn't really thinking when I did that! I think in most cases it's probably best to remove the title entirely (assuming it'll be replaced with whatever blocks are replacing the title), so I've made that update!

2021-01-21 23:15 UTC, dkoo commented on newspack-theme/js/src/hide-page-title.js
> +'use strict';
It's hard to explain what I was thinking, so I pushed my suggestions related to the above in 060c81a. Feel free to revert if you don't want these changes! But this is what I was thinking:

* I like how you localized the post types that should show each toggle option. That makes it much more future proof. I turned those items into arrays so if we wanted, we could add more post types in the future.
* For the JS, I handled both toggles in a single sidebar plugin component. I think this way it's clear when each option should be displayed, and it also makes it easier if we have more custom options to add in the future.
* I tweaked some logic around the Updated date so that if `newspack_should_display_updated_date()` is false, we just don't render that second time string at all (instead of hiding it with CSS). This matches the new treatment of hiding the title.

Let me know your thoughts—if these changes look good and work for you, I'll approve!

2021-01-21 23:18 UTC, dkoo requested changes
I like the new changes! Pushed some suggestions which aren't strictly blockers, so if you want to move ahead without them, we can revert those and merge.

2021-01-22 01:55 UTC, laurelfulford commented
Hey @dkoo! I think that looks great -- much more concise, and more "ready" for expanding if needed for different post types :) I didn't spot any issues in my testing with either the date or page title options 👍

2021-01-22 16:42 UTC, dkoo approved these changes

2021-01-22 16:43 UTC, dkoo commented
Thanks for testing! I'll give my approval but it's probably a good idea to have someone else look too. @adekbadek, can you review?

2021-01-25 11:24 UTC, adekbadek approved these changes
👌

2021-01-25 19:28 UTC, laurelfulford commented
Thanks Adam!

2021-01-25 19:28 UTC, merged