Comments: Add optional space for a comment policy
Automattic/newspack-theme pull request #1205
Opened 2021-01-12 22:54 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds the ability to add a comment policy above the WordPress comment form. 

Closes # 1102

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`. 
2. Navigate to Customize > Comment Settings
3. Confirm that you now have a checkbox to display the Comment Policy, and a text field below that for the actual policy text: 
4. 
![image](https://user-images.githubusercontent.com/177561/104383595-f2570d00-54e4-11eb-846d-9ffd0538fc4d.png)

4. Enable the checkbox, and add some text to the Comment Policy field, including some simple HTML (like bolding and links).
5. Click Update.
6. Navigate to a post with comments open, and confirm that your text is appearing between the Comment Form title and fields:

![image](https://user-images.githubusercontent.com/177561/104384177-df910800-54e5-11eb-8e3a-1394e4639b4f.png)

7. Navigate back to the customizer and uncheck the option to display the comment policy.
8. Confirm that the comment policy is now hidden. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-01-13 17:07 UTC, dkoo requested changes
This works great, I just have two small suggestions to guard against bad user input.

2021-01-13 17:07 UTC, dkoo commented on newspack-theme/inc/template-tags.php
> +			if ( $display_policy && '' !== $comment_policy ) {
This will guard against if there's only whitespace in the Comment Policy field:

```suggestion
			if ( $display_policy && '' !== trim( $comment_policy ) ) {
```

2021-01-13 17:07 UTC, dkoo commented on newspack-theme/inc/template-tags.php
> +				$comment_attributes['title_reply_before'] = '<div class="comment-policy">' . wp_kses_post( $comment_policy ) . '</div>';
This will guard against invalid HTML being entered into the Comment Policy field (source: I entered some by accident 😅):
```suggestion
				$comment_attributes['title_reply_before'] = '<div class="comment-policy">' . wp_kses_post( force_balance_tags( $comment_policy ) ) . '</div>';
```

2021-01-13 17:13 UTC, dkoo commented on newspack-theme/inc/template-tags.php
> +				$comment_attributes['title_reply_before'] = '<div class="comment-policy">' . wp_kses_post( $comment_policy ) . '</div>';
Actually, I think this would be better implemented as part of a custom sanitize callback [here](https://github.com/Automattic/newspack-theme/pull/1205/files#diff-83cc0878126972a709ebefafd5bd74d757c79f98b7309fcc0bbe8845678dc656R954), where you could create a function that runs the input through `wp_kses_post( force_balance_tags( $input ) )`. This way `force_balance_tags` doesn't have to be run on every front-end page load. What do you think?

2021-01-13 23:50 UTC, laurelfulford commented on newspack-theme/inc/template-tags.php
> +			if ( $display_policy && '' !== $comment_policy ) {
Oh good call! This has been added in c5829e2.

2021-01-13 23:52 UTC, laurelfulford commented on newspack-theme/inc/template-tags.php
> +				$comment_attributes['title_reply_before'] = '<div class="comment-policy">' . wp_kses_post( $comment_policy ) . '</div>';
Great catch! I think you just saved me from troubleshooting exploded HTML in the future! I went with the custom sanitation function, added in c5829e2.

2021-01-13 23:53 UTC, laurelfulford commented
Thanks @dkoo! I've updated the PR with your feedback - just let me know if it needs anything else!

2021-01-14 00:41 UTC, dkoo approved these changes
Looks great—thanks for the updates!

2021-01-14 23:12 UTC, laurelfulford commented
Thanks @dkoo!

2021-01-14 23:12 UTC, merged

2021-01-14 23:53 UTC, laurelfulford commented
Documentation added here: https://newspack.pub/support/themes/comments/#comment-policy