Feat: Add sticky header
Automattic/newspack-theme pull request #1254
Opened 2021-02-19 23:00 UTC by laurelfulford

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Outstanding steps to finalize this PR:

- [ ] Find a solution for Newspack Nelson's header overlap - either refactor it to make the section that's 'behind' the content actually part of the content, or update the styles to remove the overlap when the header is sticky. 
- [ ] Fully test the scaled down logo
- [ ] Finish solution for behind/beside image styles - potentially add some kind of transition; pick up the 'beside' background colour or try something else with that. 
- [ ] Test fully with ads (above; below; mobile sticky)
- [ ] Test fully with campaigns (inline top, and top, middle, bottom overlays)

### Changes proposed in this Pull Request:

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-03-01 21:49 UTC, dkoo requested changes
Ran into a couple of issues, and had a couple of suggestions (see below).

Issue 1: When using the sticky header and the simpler subpage header options, on a post with the "beside article title" featured image option, at large viewports the header gets smushed to one half of the container:

<img width="1914" alt="Screen Shot 2021-03-01 at 12 02 02 PM" src="https://user-images.githubusercontent.com/2230142/109563409-f6db8300-7a9c-11eb-82bf-f422603acba1.png">

Issue 2 (less critical): With the same set of options, while logged in at smaller viewports, the admin bar looks like it gets dropped below the top page margin. Only looked like this on the "beside article title" posts for me.

<img width="396" alt="Screen Shot 2021-03-01 at 2 48 42 PM" src="https://user-images.githubusercontent.com/2230142/109563622-40c46900-7a9d-11eb-8504-b43d0c6831f6.png">

2021-03-01 21:49 UTC, dkoo commented on newspack-theme/js/src/amp-fallback.js
> +		let scrollTimer,
What about using `requestAnimationFrame` for this instead of a `setTimeout` throttle? Theoretically it would result in better visual performance since you're tying the DOM changes to the browser repaint. In practice if you're running a fast machine then you might not see much difference, but the side benefit is also slightly simpler code. 

Something like this:

```
let currentRequest;

window.addEventListener( 'scroll', () => {
	const scrollBarPosition = window.pageYOffset;
	const remove = 200 >= scrollBarPosition;

	// Don't try to animate faster than the browser can repaint.
	if ( currentRequest ) {
		window.cancelAnimationFrame( currentRequest );
	}

	currentRequest = window.requestAnimationFrame( () => toggleHeaderClass( remove ) );
});

/**
 * @description Limit onscroll checkes and add CSS class when scrolled least 200px down the page.
 */
function toggleHeaderClass( remove = false ) {
	// At specifiv position do what you want
	if ( remove ) {
		headerContain.classList.remove( 'head-scroll' );
	} else {
		headerContain.classList.add( 'head-scroll' );
	}
}
```

2021-03-02 16:51 UTC, laurelfulford commented on newspack-theme/functions.php
> +		wp_enqueue_script( 'amp-animation', 'hhttps://cdn.ampproject.org/v0/amp-animation-0.1.js', array(), '0.1', true );
OMG 🤦‍♀️ Thanks for catching that, Derrick! I've fixed this in 6b157c9, and both the header animation and overlay campaigns seem to still work as expected with AMP enabled.

Taking a quick peek at [the popups](https://github.com/Automattic/newspack-popups/blob/846df254897441280808e35c8660550ff100cfd2/includes/class-newspack-popups-inserter.php#L520), both the theme and the plugin use the same handle for the script for both this and `amp-position-observer`, so WordPress _should_ smartly be loading only one of each (and the campaigns were probably "saving" the theme from the bad URL in my earlier testing), but let me know if you spot any further issues!

2021-03-02 19:10 UTC, laurelfulford commented
Thanks Derrick! 

> Issue 1: When using the sticky header and the simpler subpage header options, on a post with the "beside article title" featured image option, at large viewports the header gets smushed to one half of the container:

This one is a bit tough, because a) the weird to-the-side placement as designed (to avoid having the logo split over the center 'part'), and b) it's not something we can change with AMP on scroll (AMP really limits the kinds of animations you can do). It's definitely a bit weird as you scroll, though, and even more so with the left-aligned logo.

I opted to make the header stretch the width of the site only when the sticky header is enabled, so it won't change live sites unless they turn that on (I believe the combo of the beside image and the subpage header is not super common, but I know I've seen it at least once in the wild). I also added a slight dark gradient when the header is 'docked' to hopefully avoid contrast issues with really light images. I'm a bit on the fence about the centered logo in this case, but overall, I feel like it's _less_ odd than the left-heavy version:

![image](https://user-images.githubusercontent.com/177561/109700514-b3d5ea00-7b46-11eb-9e17-042deee53682.png)

![image](https://user-images.githubusercontent.com/177561/109700532-b9cbcb00-7b46-11eb-92c8-c646b4c4e40b.png)

![image](https://user-images.githubusercontent.com/177561/109700708-fbf50c80-7b46-11eb-9e64-031a4cbfd38f.png)

![image](https://user-images.githubusercontent.com/177561/109700733-031c1a80-7b47-11eb-8fe2-097962287a25.png)

Some other options could be:

1. Same as the above fix, but don't center the logo, so it's not in the 'split' -- keep it to the left, regardless of logo setting.
2. Only move the search to the far right, but keep the current logo placement to the left side, either fully to the left or centered over the solid colour. 

Let me know what you think, and if there's anything else I should try! 

> Issue 2 (less critical): With the same set of options, while logged in at smaller viewports, the admin bar looks like it gets dropped below the top page margin. Only looked like this on the "beside article title" posts for me.

This doesn't look like it's specific to the image-beside placement -- it seems to be happening for me on any post or page where I have AMP disabled and the Campaigns plugin enabled. AMP still loads some of its styles in that case, which results in some other low-key weirdness -- another example is that it reduces the space between the Homepage Posts block images and the text under them by just enough to look weird, because it makes the images `display: block`.

In this case, the culprit looks like these styles:

```
html.i-amphtml-fie:not(.i-amphtml-inabox) > body, 
html.i-amphtml-singledoc:not(.i-amphtml-inabox) > body {
    position: relative !important;
}
```

... and I can recreate this on master as well. I've created [a separate issue for this here](https://github.com/Automattic/newspack-theme/issues/1282); I'm not entirely sure I'd class it as a theme issue, but it may be the most logical place to fix it. 

Just let me know if you have any questions about either of these!

2021-03-02 19:11 UTC, laurelfulford commented on newspack-theme/js/src/amp-fallback.js
> +		let scrollTimer,
Ah, that's much nicer, and works well! Updated in 5d9482a :)

2021-03-02 19:11 UTC, laurelfulford commented on newspack-theme/js/src/amp-fallback.js
> +	const body = document.getElementsByTagName( 'body' )[ 0 ],
That's a great question! 😅 No idea, but it does as of 5d9482a.

2021-03-05 18:46 UTC, dkoo commented on newspack-theme/functions.php
> +		wp_enqueue_script( 'amp-animation', 'hhttps://cdn.ampproject.org/v0/amp-animation-0.1.js', array(), '0.1', true );
Cool, I think you're right about the matching handle. Thanks for fixing!

2021-03-05 18:59 UTC, dkoo approved these changes
I see what you mean about the challenges of the sticky header over the "split" featured image template. I like the solution you've landed on here, although I can see how it might look strange in certain live contexts. But the fact that it shouldn't affect any existing sites unless they turn on the sticky header should be a good safety, and I think this might be one of those things that would need some custom CSS to deal with particular site logos that might look off with these styles.

All that said, let's go with your current solution and we can revisit if it causes any problems for live publishers. I think it's better than the "squished" look, personally.

2021-03-09 18:03 UTC, jeffersonrabb commented
I think we should put this PR on hold for the time being. I suspect it will be widely adopted and will lead to many minor feature requests, and with @laurelfulford out of pocket for a while this might put us in a suboptimal situation. Let's reassess when and how to release this when we have a clearer understanding of how we will be able to support and develop the feature.

2021-08-17 19:00 UTC, laurelfulford commented
I've gone through and retested this PR, made some tweaks and resolved some conflicts. Though it's already been reviewed and approved by @dkoo, I would appreciate a second look just to make sure nothing odd was introduced. 

Apologies again for this massive amount of changes, and thanks in advance for the review!

2021-08-23 19:39 UTC, miguelpeixe requested changes
It looks great! Just missing that typo on the URL.

As for the Joseph margin, it does not look broken to me. It also behaves as expected when combined with an "above header" campaign. I wouldn't know how we would maintain the margin while scrolling through any above header content that might exist.

https://user-images.githubusercontent.com/820752/130508901-71bc992c-a7ba-4e1f-bc38-2e451361582e.mov

2021-08-23 19:39 UTC, miguelpeixe commented on newspack-theme/functions.php
> +		wp_enqueue_script( 'amp-animation', 'hhttps://cdn.ampproject.org/v0/amp-animation-0.1.js', array(), '0.1', true );
@laurelfulford looks like this typo still exists 😅

2021-09-21 19:09 UTC, laurelfulford commented
Gah, thanks @miguelpeixe! 🤦‍♀️ I completely missed your review, apologies!

URL is _actually_ (finally!!) fixed in 833491c -- on top of missing it the first time, I had to go back and find the comment about exactly what was wrong with it, I stared at it forever expecting 'animation' to be misspelled for some reason 😅

2021-09-23 18:43 UTC, miguelpeixe approved these changes

2021-09-23 18:44 UTC, miguelpeixe commented
> I stared at it forever expecting 'animation' to be misspelled for some reason 😅

Worst feeling ever! 😅 

>  I'm happy to leave it as is!

It has the behavior I'd expected, I wouldn't know how to make it better!

2021-09-28 15:09 UTC, laurelfulford commented
Thanks @miguelpeixe! 🙌 Excited to see this one finally land!

2021-09-28 15:09 UTC, merged

2021-09-28 16:48 UTC, yogeshbeniwal commented
Congratulations @laurelfulford on such a large and well thought one. 

In my view, Sticky header with all the menus take significant space on the screen. For good Ux if an option can be added for no sticky header on home page, that then can be combined by user with simple header on subpages option.

2021-09-29 15:36 UTC, naitian commented
A note (in case anyone else runs into this) and a question:

Setting `overflow: hidden` on `.site-content` breaks any `position: sticky` within a page. We were using this on The Michigan Daily for [scrolly-telling pieces](https://www.michigandaily.com/campus-life/umich-class-of-2025-by-the-numbers-and-their-hopes-for-college/).

I've patched this by adding some custom CSS which sets `overflow: initial` on `.site-content`, but I'm wondering if / what this might break? FWIW we don't plan on using a sticky header, but we also haven't seen any issues with full-width elements? Should I replace the `position: hidden` on `#page`?

2021-09-29 16:08 UTC, laurelfulford commented
Eep, thanks @naitian! 

The only purpose for the `overflow: hidden` was the full-width blocks, but looking at Michigan Daily on a couple different browsers, I also don't see the odd side-scroll either! I don't think removing it shouldn't cause any other issues. (If you do notice this somewhere, re-adding `overflow: hidden` on `#page` should help!). 

I'm going to create an issue to re-investigate whether the `overflow: hidden` is still needed; it might be that it can be removed from the theme entirely. Thanks for flagging this!

2021-09-29 16:33 UTC, naitian commented
Great, thank you!

2021-10-19 19:52 UTC, laurelfulford commented
@yogeshbeniwal Thanks for your suggestion (I'm sorry I missed it earlier)! I'm going to see if we get more feedback to that end before adding more options, but if you'd like to add this in the short-term to a site, you could use the following Custom CSS:

```
@media (min-width: 782px) {
	.newspack-front-page.h-stk .site-header {
		position: initial;
	}
}
```

Including the media query will mean the header is still sticky on mobile screens when it's smaller, but you could also remove that bit to have it always be fixed at the top.

2021-10-20 05:18 UTC, yogeshbeniwal commented
@laurelfulford Its working, thank you