Add ads background color theme option
Automattic/newspack-theme pull request #1326
Opened 2021-04-06 16:28 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a new theme option to control the background color of the Ads in the Customizer (Colors > Ads Background Color)

### How to test the changes in this Pull Request:

1. Navigate to Customizer > Colors > Ads Background Color
2. By default, the radio should be on Default
3. Switch to Custom, you should have access to a color picker
4. Select a background color and Save.
5. Check all the ads around your site to see if they have the new background color, and some padding.

__Note: make sure you test all the different solutions to display a ad on a Newspack site, including the widget, the ad units block...__

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-04-23 15:13 UTC, adekbadek requested changes
The custom ad background color will not be applied unless the site has custom colors enabled:

https://github.com/Automattic/newspack-theme/blob/ee67c55c118ab2d43a40d8e63f83fc3ff84d9c8e/newspack-theme/functions.php#L692-L695

2021-04-23 15:13 UTC, adekbadek commented on newspack-theme/inc/color-patterns.php
> +			}
Why should color settings influence spacing 👆?

2021-05-21 11:12 UTC, thomasguillot commented
> The custom ad background color will not be applied unless the site has custom colors enabled
Fixed in https://github.com/Automattic/newspack-theme/pull/1326/commits/ecdb6ca22abd0ff69bf72b3de642d02d12b7165c

2021-05-21 11:15 UTC, thomasguillot commented on newspack-theme/inc/color-patterns.php
> +			}
If I don't add the padding, then we'd get a weird stripe of colour

![Screenshot 2021-05-21 at 12 14 16](https://user-images.githubusercontent.com/177929/119128883-219aff00-ba2e-11eb-8da7-7505d49a3856.png)

VS

![Screenshot 2021-05-21 at 12 14 00](https://user-images.githubusercontent.com/177929/119128896-25c71c80-ba2e-11eb-8e10-922be9c713f7.png)

2021-05-25 11:19 UTC, adekbadek approved these changes

2021-05-25 13:01 UTC, merged