fix: figcaption rendering bug in Safari
Automattic/newspack-theme pull request #1382
Opened 2021-06-23 21:47 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes an [obscure Safari rendering bug](https://github.com/ampproject/amp-wp/issues/6035) which causes captions inside image blocks with an alignment set to render in the wrong position.

### How to test the changes in this Pull Request:

1. Add an image block to a post and choose an image that has a caption. Set an alignment on the block (left, center, or right).
2. On `master`, view the post in Safari. Observe that the caption appears in the wrong place (if you don't see the bug, try hard-refreshing the post):

<img width="854" alt="Screen Shot 2021-06-23 at 3 44 30 PM" src="https://user-images.githubusercontent.com/2230142/123172150-f135ee80-d439-11eb-8ed9-a857efdbabc0.png">

3. Check out this branch and hard-refresh the post. Confirm that the caption now renders as expected.
4. Re-test with all alignment options and no alignment options, and in another browser to ensure that the fix doesn't change anything outside Safari.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-06-23 22:11 UTC, laurelfulford requested changes
There's a version of this fix [that's only applied to mobile in the _blocks.scss](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/sass/blocks/_blocks.scss#L772-L778) file though this location makes more sense! That one should probably be removed, too as part of this PR. 

The theme did include this fix for screen sizes at one point, but it causes smaller floated images to have their captions run wider than the images themselves. There's some more information and screenshots for that here:

https://github.com/Automattic/newspack-theme/pull/1109

IIRC the too-small-images-and-wide-captions issue was only reported once while this fix was in the theme, so I think that might be an acceptable trade-off at this point, since the caption gap issue has come up pretty often. I've been manually adding CSS fixes to the sites that report it, but it's probably better to go the other way around and manually undo it on any sites that report the small-image-wide-caption issue instead (I remember the site that originally reported the issue, so I can take care of that ahead of this being merged). 

Let me know what you think about the above! If it sounds okay, I think this will be good to go once the near-duplicate styles are removed from _blocks.scss.

2021-06-23 22:48 UTC, dkoo commented
Wow, thanks for the historical context around this bug! That's a pretty infuriating trade-off—either we fix the bug in Safari at the expense of introducing another bug with smaller images in all browsers, or we leave the bug in Safari...

As discussed off GitHub, maybe the best hybrid approach is to fix the bug only in Safari and leave core styles active for all other browsers. [This StackOverflow thread](https://stackoverflow.com/questions/16348489/is-there-a-css-hack-for-safari-only-not-chrome) discusses some CSS hacks that supposedly work to target CSS in specific versions of Safari. I tried the `@supports ( -webkit-hyphens: none )` hack that targets Safari 9+ (introduced 2015) and it seems to do the trick. I also removed the duplicate styles with the media query targeting only mobile viewports in `_blocks.scss` as you requested. 64c9596

2021-06-25 00:05 UTC, laurelfulford approved these changes
Thanks @dkoo!

I took this for a spin both locally and using Browserstack; I can confirm this fix works, and, by using a smaller image, confirm that it's only being applied to Safari 9+ (on Safari 8, and other browsers, the smaller image's caption matches its width). 

Thanks for tackling this! I'm looking forward to never hearing about this one again, it's been an annoying one 😄

2021-07-05 16:16 UTC, laurelfulford commented
@dkoo I'm on a bit of a merging spree so I'm going to go ahead and merge this one! :)

2021-07-05 16:16 UTC, merged

2021-07-05 16:17 UTC, dkoo commented
Oh, thanks for merging!