feat: customizing svg icon for social media with a hook
Automattic/newspack-theme pull request #1396
Opened 2021-07-01 10:01 UTC by uptimizt

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-07-21 17:07 UTC, laurelfulford requested changes
Thanks for submitting this PR, @uptimizt!

One thing I noticed while testing is that you can pass any markup to the menu, not just an SVG -- for example:

```
add_filter('newspack_get_social_link_svg', function ( $svg, $uri, $size, $title ) {
    if ( ! empty( $svg ) ) {
        return $svg;
    }
    if ( strpos( $uri, 'telegram' ) === false ) {
        return $svg;
    }
    return '<script>alert("hello world!!");</script>';
}, 11, 4);
```

... will fire an alert if you include a link with telegram in it in the social menu. 

With opening this up to be filter-able, what do you think about adding some kind of sanitation to make sure only SVG-related elements are passed through? The theme [already has a function](https://github.com/Automattic/newspack-theme/blob/c2cd40f731c6c2173f8f4346281823f94d9b95cb/newspack-theme/functions.php#L745-L770) that returns allowed SVG tags that's used [in other parts of the theme](https://github.com/Automattic/newspack-theme/blob/5fa724dddf7cd0e3b3ace5ee52b509bfa3199945/newspack-theme/header.php#L57) with `wp_kses` -- it may need expanding over time to make sure it allows all of the SVG tags someone might use, but so far it covers everything used by all of the SVGs in the theme.

Let me know what you think, and if you have any questions at all - thanks!

2021-07-28 06:54 UTC, uptimizt commented
@laurelfulford thank you for the feedback.

I added wp_kses.

But I guess what if users want to add a PNG icon? or WebP?

2021-07-29 00:58 UTC, laurelfulford commented
Thanks for the update, @uptimizt!

> But I guess what if users want to add a PNG icon? or WebP?

The theme only uses SVGs in that menu, so it seems like overkill for the filter to support other image types when the theme itself doesn't use them. 

By keeping everything SVG, it makes it much easier to standardize the icons appearance with what's included in the theme, and the icons will also automatically change colour to have sufficient contrast when you use the different header background options. They can also be customized in a much more standard fashion (eg. changing the fill in the Custom CSS will be applied to all of the icons). 

I think for now it keeps things much more straight forward just to support the one format. But please let me know if you have any questions at all about the above!

2021-07-29 00:59 UTC, laurelfulford approved these changes

2021-07-29 01:00 UTC, merged