Homepage Posts Block: Style adjustments for widget block areas
Automattic/newspack-theme pull request #1407
Opened 2021-07-06 23:46 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR is in advance of the Homepage Posts block being able to be added to widget areas in WordPress 5.8. It's to help make sure there are no major visual issues. 

Unfortunately this will be a tedious one to test, since it involves checking the different themes, with different custom colour settings. Apologies in advance, and please let me know if there's anything I can do to make testing this easier (like setting up the PR on a Jurassic Ninja site, to save some steps). 

See #1372

### How to test the changes in this Pull Request:

1. Start with a test site running the latest WordPress 5.8 release candidate, and the Newspack Default theme.
2. Navigate to Widgets > Appearance and add the following blocks Sidebar and Slide-out Sidebar widget areas:
    * Homepage Posts block - default settings, with the "Section Header" filled out
    * Homepage Posts block - image behind
    * Homepage Posts block - image beside
    * Add a Header block, and give it the CSS class `accent-header`. 
    * Add at least one Navigation Menu Widget (under 'Legacy widgets'), and assign a menu.
3. Navigate to the Customizer, and set the following settings:
     * Under Header > Slide-out Sidebar, turn on and check the option to show the widgets in the mobile menu.
     * Under Header > Subpage Header and enable the subpage header.
     * Change the colour palette away from the default, and pick some custom fonts. 
     * Assign menus to the primary, secondary, tertiary and social locations.
4. View the footer widget area, slide-out sidebar, subpage sidebar and mobile menu; note the appearance of existing things, like the menus; also note the appearance of the Homepage Posts block - 

<details>
<summary><strong>Slide-out Sidebar</strong></summary>

### Navigation Menu widget 
* displaying correctly

![image](https://user-images.githubusercontent.com/177561/124670489-e8e1a880-de68-11eb-92b5-4150b9f98f09.png)

### Homepage posts 
* fonts are very small

![image](https://user-images.githubusercontent.com/177561/124670465-e0896d80-de68-11eb-8a29-18d0d3b78981.png)

* image behind doesn't fill space, and there's almost a padding around the edge

![image](https://user-images.githubusercontent.com/177561/124670435-d7000580-de68-11eb-8362-999cbcd2dc2d.png)

</details>

<details>
<summary><strong>Mobile menu</strong></summary>

### Regular menus (Tertiary, primary, secondary, social)
* Displaying correctly

![image](https://user-images.githubusercontent.com/177561/124670273-97391e00-de68-11eb-86fc-0f5e31e1bbb7.png)

### Homepage Posts block 
* header, byline invisible; entry date hard to read against dark background

![image](https://user-images.githubusercontent.com/177561/124670316-a750fd80-de68-11eb-9261-ff7253a88dd4.png)

* image behind - padding around the image

![image](https://user-images.githubusercontent.com/177561/124670358-b9cb3700-de68-11eb-8f08-7d27cae225a0.png)
</details>

<details>
<summary><strong>Subpage slide-out menu</strong></summary>

### Regular menus
* There's an existing display issue with the Tertiary Menu that is filed here: #1406; otherwise it's displaying as expected.

![image](https://user-images.githubusercontent.com/177561/124671130-e6cc1980-de69-11eb-9ec8-8640c893ee1a.png)

### Homepage Posts
* fonts are very small
![image](https://user-images.githubusercontent.com/177561/124671182-f9465300-de69-11eb-825d-8a330639ee31.png)

* image-behind doesn't fill the available space: 
![image](https://user-images.githubusercontent.com/177561/124671214-0400e800-de6a-11eb-83cf-9905c2f01240.png)

### Navigation Widget

* displaying correctly 

![image](https://user-images.githubusercontent.com/177561/124671354-33175980-de6a-11eb-90a5-6d563da087ae.png)
</details>

<details>
<summary><strong>Footer widget area</strong></summary>

### Homepage Posts block
* fonts are very small

![image](https://user-images.githubusercontent.com/177561/124671467-5e9a4400-de6a-11eb-860e-6f591563d3ed.png)
</details>

<details>
<summary><strong>Above Copyright widget area</strong></summary>

Overall, this is a terrible location for anything but text or image widgets, but we should fix the worst of the visual issues with the homepage posts block.

### Homepage posts block

* Byline wraps to seperate line
* When image is set to behind, it doesn't fill the available space
![image](https://user-images.githubusercontent.com/177561/124671719-c2247180-de6a-11eb-9264-e42c2caac2ad.png)
</details>

5. Apply the PR and run `npm run build`.
6. Re-review the above widget areas; confirm the issues are fixed with the Homepage Posts block, but without affecting things like spacing or font sizes on the existing elements, like menus and Navigation widgets.

<details>
<summary><strong>Slide-out Sidebar</strong></summary>

### Navigation Menu widget 

### Homepage posts 
* Fonts are a bit larger

![image](https://user-images.githubusercontent.com/177561/124672410-dc128400-de6b-11eb-9f8e-6dc7c8cbcd25.png)

* image behind option fills the available space
![image](https://user-images.githubusercontent.com/177561/124672442-e6348280-de6b-11eb-81e4-47ecbf05afa9.png)

</details>

<details>
<summary><strong>Mobile menu</strong></summary>

### Homepage Posts block 
* Contrast issues are fixed against dark backgrounds:

![image](https://user-images.githubusercontent.com/177561/124672561-15e38a80-de6c-11eb-8da3-cf8ae5d8867d.png)

* When you switch the primary colour to a lighter colour, the contrast is still good: 
![image](https://user-images.githubusercontent.com/177561/124672719-5cd18000-de6c-11eb-9642-1c6c3084efe9.png)

* with the image behind setting, the image now fills the available space
</details>

<details>
<summary><strong>Subpage slide-out menu</strong></summary>

### Homepage Posts
* fonts are a more standard size

![image](https://user-images.githubusercontent.com/177561/124673413-a5d60400-de6d-11eb-9cf7-3c2fb0321cfa.png)

* with the image behind setting, the image now fills the available space

</details>

<details>
<summary><strong>Footer widget area</strong></summary>

### Homepage Posts block
* fonts are more representative to what they're set to in the block, and the image behind issues are gone:
![image](https://user-images.githubusercontent.com/177561/124673618-09603180-de6e-11eb-902c-7761d2ae7001.png)

If you set the footer background to different colours, the Homepage Posts block also remains legible:

![image](https://user-images.githubusercontent.com/177561/124673708-39a7d000-de6e-11eb-8f58-0181ceb389de.png)

... and it also should work well with a lighter colour:

![image](https://user-images.githubusercontent.com/177561/124673761-50e6bd80-de6e-11eb-89f0-f02d7bc5a42d.png)

</details>

<details>
<summary><strong>Above Copyright widget area</strong></summary>

### Homepage posts block
* byline, image behind issues are resolved: 
![image](https://user-images.githubusercontent.com/177561/124673795-5f34d980-de6e-11eb-9f8d-09418083f51a.png)

</details>

7. Switch to Newspack Joseph; double check that the homepage posts block header is picking up the correct border colour (the line next to the header should be the same colour).

<details>
<summary><strong>Newspack Joseph screenshots</strong></summary>

![image](https://user-images.githubusercontent.com/177561/124674227-2f3a0600-de6f-11eb-9aba-3e427624e53f.png)

![image](https://user-images.githubusercontent.com/177561/124674242-352fe700-de6f-11eb-9b82-f3720223abb7.png)

</detail [...]

2021-07-08 21:28 UTC, dkoo requested changes
Overall this looks much better than on `master`. I saw a couple of things which may not require changes, but just in case:

1. The font size in the "Above Copyright" area is much smaller than in other widget areas—this is probably intentional, right? But it is noticeably tiny:

<img width="1243" alt="Screen Shot 2021-07-08 at 3 16 45 PM" src="https://user-images.githubusercontent.com/2230142/124992943-e4e88e80-e000-11eb-9184-1d094abcd88e.png">

2. This may be outside the scope of this PR, but Homepage Post blocks inside a Group block with a background color don't adjust their colors for contrast. (Probably much more difficult to do with a dynamic background color, right?)

<img width="568" alt="Screen Shot 2021-07-08 at 2 31 05 PM" src="https://user-images.githubusercontent.com/2230142/124993021-00ec3000-e001-11eb-95dc-d1f663794085.png">

Other than that, all works as described.

2021-07-08 21:44 UTC, dkoo requested changes
Another thing I ran into in a very specific scenario. I don't believe any other themes cause this warning.

2021-07-08 21:44 UTC, dkoo commented on newspack-katharine/inc/child-color-patterns.php
> +			background-color: ' . esc_html( newspack_adjust_brightness( $header_color, -20 ) ) . ';
I'm seeing a PHP warning referencing this line that I think is being thrown by the Customizer when Katharine is active:

```
PHP Notice:  Undefined variable: header_color in /Users/dkoo/Local Sites/newspack/app/public/wp-content/themes/repo/newspack-katharine/inc/child-color-patterns.php on line 75
```

2021-07-09 01:13 UTC, laurelfulford commented
Thanks @dkoo!

> The font size in the "Above Copyright" area is much smaller than in other widget areas—this is probably intentional, right? But it is noticeably tiny:

Yup, it is intentional -- this area isn't really meant for anything but text (like simple menus) or images, that need to operate outside of the columned layout the Footer does (think sponsored logos, a line of less important links...). Hopefully with the ability to add blocks to the widget areas, it kind of makes this one unnecessary -- you can freely layout multiple columns/groups in the Footer Layout and not be stuck with the automatically generated layout that the footer styles do by default. 

I would really hope no-one would put a homepage posts block in this spot so I left the sizing as is, but please let me know if this seems more harmful than good -- I can also add the same exception to this area (applying the font size to `.widget` but not `.widget_block`) so the blocks behave more predictably! 

> This may be outside the scope of this PR, but Homepage Post blocks inside a Group block with a background color don't adjust their colors for contrast. (Probably much more difficult to do with a dynamic background color, right?)

It would be possible, at least with the palette colours (primary and secondary), but it also turns into a massive game of whack a mole! 😄 As a work-around (like you'd have to do adding the group block to the content area with a dark background), most blocks have an option to change the block colour. I did a quick test and it looks like it works in the Footer and Mobile Sidebar areas with the Homepage Posts block:

![image](https://user-images.githubusercontent.com/177561/125008646-c5109500-e017-11eb-9e11-90dbc409870c.png)

![image](https://user-images.githubusercontent.com/177561/125008840-34868480-e018-11eb-881e-5aa08052f499.png)

2021-07-09 17:36 UTC, dkoo approved these changes
Thanks for the clarification—all looks good to me, then (except for the PHP warning I mentioned above)!

2021-07-09 17:37 UTC, dkoo requested changes
Whoops, shouldn't approve until we fix that PHP warning.

2021-07-09 21:35 UTC, laurelfulford commented
> Thanks for the clarification—all looks good to me, then (except for the PHP warning I mentioned above)!

I was having a heck of a time recreating yesterday so I didn't finish this up -- going to try to get it fixed before merging :) Looking again now!

2021-07-09 23:20 UTC, laurelfulford commented
I still can't get the error, but I don't doubt that it's happening in some case, that colour code is getting a bit nuts. I ended up fixing it by moving the styles using `$header_color` into a section already checking if that variable exists, rather than trying to set a fallback value. Please let me know if that doesn't do the trick!

2021-07-09 23:21 UTC, laurelfulford commented on newspack-katharine/inc/child-color-patterns.php
> +			background-color: ' . esc_html( newspack_adjust_brightness( $header_color, -20 ) ) . ';
This has been reworked a bit in 698ff49!

2021-07-13 16:38 UTC, dkoo approved these changes
Whoops, lost the thread on this. I no longer see the PHP error when viewing Katharine in the Customizer. Thanks!

2021-07-13 17:08 UTC, merged

2021-07-13 17:09 UTC, laurelfulford commented
Thanks! 🙌