Newspack Nelson: remove overlap when featured image is behind
Automattic/newspack-theme pull request #1482
Opened 2021-08-13 23:06 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Newspack Nelson's overlap doesn't play well with the different featured image settings.

When the 'behind' or 'beside' option is selected, the overlap is essentially 'styled away' -- this PR does the same with the 'above' image placement, which was somehow missed before. 

Closes #1481

### How to test the changes in this Pull Request:

1. Switch your test site to Newspack Nelson.
2. Create a post; add a featured image and change the position to "Above"
3. View on the front-end and note the big weird gap:

![image](https://user-images.githubusercontent.com/177561/129425903-b321f07b-c88b-4133-8797-516773155ff9.png)

4. Apply the PR and run `npm run build`
5. Refresh the post and confirm that the weird gap is now gone! 

![image](https://user-images.githubusercontent.com/177561/129425857-22938cae-8ae3-46e9-954f-dc9912a85e32.png)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-08-16 08:18 UTC, adekbadek requested changes

2021-08-16 08:18 UTC, adekbadek commented on newspack-nelson/sass/style.scss
> +.single-featured-image-above {
With this change, when "Use simple header on subpages" option is on, on a single post with "above" featured image, a header with a solid colour is transparent. This makes the clickable elements invisible:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/7383192/129533142-34ab2d63-e7f2-48f5-b5ac-15d2301ddd75.png">

2021-08-16 17:59 UTC, laurelfulford commented on newspack-nelson/sass/style.scss
> +.single-featured-image-above {
D'oh - thanks Adam! 🤦‍♀️ I'm not sure what I was thinking, but this is fixed in 4a628dc.

2021-08-17 08:47 UTC, adekbadek approved these changes
🙌

2021-08-17 15:03 UTC, laurelfulford commented
Thanks Adam! 🎈

2021-08-17 15:04 UTC, merged