feat: add option to change archive title format
Automattic/newspack-theme pull request #1503
Opened 2021-09-07 19:50 UTC by laurelfulford

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds an option to remove the archive page title 'prefixes', eg. removing 'Category:', 'Tag:', 'Author:'...

Given the different kinds of archives (especially with different CPTs) this seemed like the simplest approach, and closest mimics what's possible with the theme visually now. But if we do find that publishers want more options for these titles, we can explore that further in a different PR. 

Closes #1493

### How to test the changes in this Pull Request:

1. Apply this PR.
2. Navigate to Customizer > Template Settings > Archive Settings, and confirm you now have an option to change the Archive Title. 
3. Confirm that the option labels make sense. 
4. Try switching to "Only Archive Name"; confirm that the prefix part of the archive titles are removed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-09-08 13:41 UTC, miguelpeixe requested changes
Nice addition and working as described!

I think we should also change how the author name is aligned with the thumbnail with the new archive title format. Currently, it's displayed off-centered:

![author-archive](https://user-images.githubusercontent.com/820752/132520352-c246bf21-347e-47d7-936a-5992db76312f.png)

2021-09-08 20:36 UTC, laurelfulford commented
@miguelpeixe That's a really good point! It just looks odd with the author archives, if they have nothing else displaying.

Unfortunately this adds a couple additional steps to the testing, to make sure I didn't mess anything up with this change 😬 Specifically:

1. Test with just the author name showing on the archive pages, and make sure it's vertically centered.
2. Under Customizer > Author Bio, turn on the author email address, and make sure it looks okay.
3. Edit the current user (you should have an 'Edit User' link in the Admin Toolbar when viewing an author archive), and add text to the "Biographical Info" field. 
4. Make sure the archive looks okay with the bio description showing. 
5. Lastly, switch to Newspack Sacha -- which centres the author bio at the top -- and repeat steps 1-4 to make sure it looks okay. 

I've attached some screenshots to show roughly what each of these should look like -- just let me know if I can provided any more info to make retesting easier!

Newspack Default - author name only:

![image](https://user-images.githubusercontent.com/177561/132581676-a01ebf16-f1de-46ea-bcf9-7ee77467053e.png)

Newspack Default - author name & email:

![image](https://user-images.githubusercontent.com/177561/132581648-168b1fdb-238c-44ee-a332-4b7e05df9a99.png)

Newspack Default - author name, bio and email (and social links, too!):

![image](https://user-images.githubusercontent.com/177561/132581630-b38f120b-b2d9-4c92-abad-1d0503e2813f.png)

Newspack Sacha - author name only: 

![image](https://user-images.githubusercontent.com/177561/132581007-016bd7c0-27cb-44e2-9611-b5565198a475.png)

Newspack Sacha - author name & email: 

![image](https://user-images.githubusercontent.com/177561/132580946-0df40d3f-29b9-4fee-8b39-8eefcb0d2385.png)

Newspack Sacha - author name, bio and email (and social links, too!):

![image](https://user-images.githubusercontent.com/177561/132581075-5fe70406-4488-4e97-a88c-1edff26463df.png)

2021-09-09 15:16 UTC, miguelpeixe approved these changes
Thank you for revising! It is looking great on all scenarios across all child themes! 💯

2021-09-09 22:26 UTC, laurelfulford commented
Thanks @miguelpeixe! 🙌

2021-09-09 22:26 UTC, merged

2021-09-20 23:07 UTC, gamebits commented
Our spot checks indicate that this feature did indeed resolve the SEO issue is was created to address. 🎉