Update header colour logic
Automattic/newspack-theme pull request #1506
Opened 2021-09-09 00:51 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the header colour code defaults. 

Originally some formatting feedback of mine resulted in an issue with Newspack Nelson, but when testing that more fully, I found a couple other odd cases where the colours do not behave as expected when you don't have a specific header colour set (or in cases where the header colour should be picking up the primary colour as a default, but it wasn't picking up the _updated_ primary colour). So this PR tweaks all to the header colour assignment code, taking into account the convoluted ways different child themes work (eg. Newspack Sacha, Katharine and Joseph all use greys for their default solid headers). 

I tested this against an older version of the theme, and took how the different colour/header settings acted there as a source of truth, since it's pretty convoluted! 😐 For context, the solid header background option predates the option to actually change the header colour, so the theme-to-theme defaults were different because they were the only options there were. 

Closes #1505.

### How to test the changes in this Pull Request:

1. Apply the PR. 
2. Navigate to Customizer > Colours, and set it to the default header colours, then default colours.
3. Navigate to Customizer > Header Settings > Appearance and check Solid Background. 

4. **Switch the theme to Newspack Default.**
 a. Check the header and mobile menu; confirm both are using Newspack blue:

![image](https://user-images.githubusercontent.com/177561/132597726-53374d2b-da47-43ad-89f4-5811d5fa6e2e.png)

![image](https://user-images.githubusercontent.com/177561/132597739-17f0182d-b53c-4c57-88c6-3c54da956cab.png)

 b. Navigate to Customizer > Colours, and turn on the custom colours, and change the primary colour.
 c. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:
     
![image](https://user-images.githubusercontent.com/177561/132597975-20db7ea0-b018-4dbb-a142-46e402ac3cb5.png)

![image](https://user-images.githubusercontent.com/177561/132597988-dd0a0c19-1d3f-4db3-9030-abd68847b262.png)

 d. Navigate to Customizer > Colours and turn on the custom header colour, and change the header colour.
 e. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:
     
![image](https://user-images.githubusercontent.com/177561/132598266-98282a3b-757f-427e-8c92-3cdb8580d326.png)

![image](https://user-images.githubusercontent.com/177561/132598284-260f8f4a-2ea4-4b7f-91b8-a2bdf78b1884.png)

5. **Repeat Step 2, and switch to Newspack Joseph:**
 a. Check the header and mobile menu; confirm both are using very dark grey (basically black):

![image](https://user-images.githubusercontent.com/177561/132600588-b25c68d1-22ce-426c-8cd0-28085be844f3.png)

![image](https://user-images.githubusercontent.com/177561/132600599-9178d876-a259-41a2-adb6-718639d292bf.png)

 b. Navigate to Customizer > Colours, and turn on the custom colours, and change the primary colour.
 c. Confirm that the header stays dark grey/black, but the mobile menu picks up your primary colour:

![image](https://user-images.githubusercontent.com/177561/132601373-b305382e-2b90-4f8a-b438-038a270efd4b.png)

![image](https://user-images.githubusercontent.com/177561/132601386-999a6b4f-56b5-4d8c-af1e-3655c388da28.png)

 d. Navigate to Customizer > Colours and turn on the custom header colour, and change the header colour.
 e. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:

![image](https://user-images.githubusercontent.com/177561/132601628-2e96fbab-7671-4010-935b-53a55d916d61.png)

![image](https://user-images.githubusercontent.com/177561/132601634-e5178332-caf0-4491-9a97-abea511b3432.png)

6. **Repeat Step 2, and switch to Newspack Katharine:**
 a. Check the header and mobile menu; confirm that the header is using dark grey, and the mobile menu is using the primary colour:

![image](https://user-images.githubusercontent.com/177561/132602239-71089c2b-445c-4809-aaa5-41c813340621.png)

![image](https://user-images.githubusercontent.com/177561/132602250-4a129596-d7ae-4b37-b7db-6b09f2ee3b34.png)

 b. Navigate to Customizer > Colours, and turn on the custom colours, and change the primary colour.
 c. Confirm that the header stays grey, and the mobile menu picks up your new primary colour:

![image](https://user-images.githubusercontent.com/177561/132602431-d6d1eff6-5cee-4c30-ba89-dd2c56f20478.png)

![image](https://user-images.githubusercontent.com/177561/132602441-0fe57583-9f7a-4792-99c4-60e9721765d2.png)

 d. Navigate to Customizer > Colours and turn on the custom header colour, and change the header colour.
 e. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:

![image](https://user-images.githubusercontent.com/177561/132602557-e6e5514c-e727-4613-99b1-a25d38082d14.png)

![image](https://user-images.githubusercontent.com/177561/132602570-031a71e3-d6f0-4dbd-8889-0fedb2b6f148.png)

7. **Repeat Step 2, and switch to Newspack Nelson:**
 a. Check the header and mobile menu; confirm that the header and mobile menu are both using the primary colour:

![image](https://user-images.githubusercontent.com/177561/132602858-30ba51a4-6a05-40d6-8420-e9eeb60dc0f2.png)

![image](https://user-images.githubusercontent.com/177561/132602869-1e86d5ea-6120-4454-a4ce-9ea711ce6b29.png)

 b. Navigate to Customizer > Colours, and turn on the custom colours, and change the primary colour.
 c. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:

![image](https://user-images.githubusercontent.com/177561/132603028-b80a200a-fd8a-4f1d-8060-3c901554a387.png)

![image](https://user-images.githubusercontent.com/177561/132603039-40e9c271-5824-4407-a530-ff213ec38ab6.png)

 d. Navigate to Customizer > Colours and turn on the custom header colour, and change the header colour.
 e. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the front-end:

![image](https://user-images.githubusercontent.com/177561/132603134-7429575c-5067-4ce4-af52-e58a6d2cf38d.png)

![image](https://user-images.githubusercontent.com/177561/132603143-15300165-8dfd-42a7-b46b-4bdb3b13f262.png)

8. **Repeat Step 2, and switch to Newspack Sacha:**
 a. Check the header and mobile menu; confirm that the header is dark grey and mobile menu is the primary colour:

![image](https://user-images.githubusercontent.com/177561/132603454-8c1a3a42-ee34-4dd2-b961-e1927c64f4b1.png)

![image](https://user-images.githubusercontent.com/177561/132603482-d9b78960-daa2-44c9-a579-4a9e4f93452f.png)

 b. Navigate to Customizer > Colours, and turn on the custom colours, and change the primary colour.
 c. Confirm that the header stays grey, and the mobile menu picks up your new primary colour:

![image](https://user-images.githubusercontent.com/177561/132603625-3e6995f1-7f6a-4f74-86f7-22d4fd793466.png)

![image](https://user-images.githubusercontent.com/177561/132603615-5238de5d-3976-4853-b41e-9c009febef78.png)

 d. Navigate to Customizer > Colours and turn on the custom header colour, and change the header colour.
 e. Confirm that it's being picked up by the header and mobile menu backgrounds, both in the customizer and on the fr [...]

2021-09-13 13:11 UTC, adekbadek requested changes
Works as expected, just one code quality remark.

2021-09-13 13:11 UTC, adekbadek commented on newspack-joseph/inc/child-color-patterns.php
> +			$header_color = '#111';
Here and in all other cases - this reassignment is not necessary, at this point the value will not have changed after the assignment on line 13.

2021-09-13 21:35 UTC, laurelfulford commented on newspack-joseph/inc/child-color-patterns.php
> +			$header_color = '#111';
🤦‍♀️ Gah, thanks for catching that, @adekbadek ! I fixed this in the three themes that don't actually use the primary colour as the default header background in d2eb4ef (Joseph, Katharine, and Sacha).

2021-09-14 07:44 UTC, adekbadek commented on newspack-joseph/inc/child-color-patterns.php
> +			$header_color = '#111';
Thanks! And I was not entirely right - didn't notice that `$primary_color` is actually updated in the other three :D Anyway, all good now!

2021-09-14 07:44 UTC, adekbadek approved these changes

2021-09-14 16:26 UTC, laurelfulford commented
Thanks @adekbadek!

2021-09-14 16:26 UTC, merged