extend/duplicate .widget-title and .accent-header styles to misspelled class name caused by known bug in Gutenberg to prevent nested legacy widget titles from losing styles
Automattic/newspack-theme pull request #1532
Opened 2021-10-01 01:04 UTC by hawkeye126

2021-10-01 01:09 UTC, hawkeye126 commented
Steps to replicate:
1) Using default WordPress and News Pack Theme (any child theme)
2) Add a widget group
3) Add two legacy widgets of type meta
4) Add widget titles
5) On front end you will see the `.widget-title` and `.accent-header` classes are missing

Before:
![Screen Shot 2021-09-30 at 6 06 00 PM](https://user-images.githubusercontent.com/1033613/135550338-497f1575-a858-4ac9-8ced-e7469a58c90b.png)

After:
![Screen Shot 2021-09-30 at 6 05 38 PM](https://user-images.githubusercontent.com/1033613/135550356-7b1ecf06-e507-47d7-a03f-8a3c7ff08056.png)

2021-11-23 13:10 UTC, adekbadek commented
Pinging @laurelfulford ;)

2021-11-24 19:24 UTC, laurelfulford requested changes
Thank you for this PR, @hawkeye126! 

It looks like updates will need to be made to more places to fix this everywhere -- the Newspack theme is pretty convoluted, between its customization options and different child themes. Unfortunately this means making these kinds of fixes can be pretty intensive! :) 

I've gone through and tested different cases with the different themes, to try to capture most of the cases I'm talking about. You're welcome to update your PR, but of course I understand if this is a bit much! Please let me know if you'd like me to take a swing at this. 

Thank you!

**Newspack (parent theme):**
* The sidebar widget title uses the 'primary' colour for text, so it should change when that's changed under Customizer > Colors - this is added through the `accent-header` class, but it will likely need the `#secondary .widgettitle` selector added to what's there ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/color-patterns.php#L347-L350))

![image](https://user-images.githubusercontent.com/177561/143288631-51f65a44-8316-43d1-86c3-820cab959d85.png)

* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel  -- like the above, `#secondary .widgettitle` will probably need to be added to what's there ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/typography.php#L389-L392)).

![image](https://user-images.githubusercontent.com/177561/143288932-fd86968e-0766-42e4-b16f-9d3c64d49367.png)

* In the footer, the widget titles should not have the underline - that's only added to the widgets in the sidebar area:

![image](https://user-images.githubusercontent.com/177561/143289102-597ed710-f116-414b-8baf-adc593c29460.png)

* In the footer, when you set a darker background colour under Customizer > Colors, the widget titles should be white ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/inc/color-patterns.php#L303-L309))

![image](https://user-images.githubusercontent.com/177561/143293968-8ea13474-98b7-4807-b105-46c040da467f.png)


**Newspack Joseph**
* The sidebar widget title should have a horizontal line next to it ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-joseph/sass/style.scss#L117-L147))
* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-joseph/inc/child-typography.php#L76-L79))
![image](https://user-images.githubusercontent.com/177561/143291301-e2ee0cdb-e723-425d-bdc0-d9bd72a1ff96.png)

* In the footer, when you set a darker background colour under Customizer > Colors, the widget titles should be white ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-joseph/inc/child-color-patterns.php#L72-L76))

![image](https://user-images.githubusercontent.com/177561/143294554-a2572f21-9f85-44e3-9fb6-8d4e6a7f1db3.png)

**Newspack Katharine**
* Similar to the default theme, the sidebar widget title should pick up the primary colour set under Customizer > Colors ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L43-L45))

* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43))
![image](https://user-images.githubusercontent.com/177561/143292225-1c42283a-7639-49e0-8fd8-1bf929cf88fb.png)

* The footer widget title should also be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43))
* In the footer, the widget title should not be picking up the little 'above title' accent
![image](https://user-images.githubusercontent.com/177561/143295636-e4a73806-ee45-476d-9b25-132ee2eb5ba7.png)

**Newspack Nelson**

* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-nelson/inc/child-typography.php#L36-L49))
![image](https://user-images.githubusercontent.com/177561/143298752-0e2dc6d6-78ab-4bfe-a7cd-0be2ea1f3f15.png)

* The footer widget title should also be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-nelson/inc/child-typography.php#L46-L49))
![image](https://user-images.githubusercontent.com/177561/143298317-ab74f041-2d28-42a4-ade7-890dfe774c94.png)

**Newspack Sacha**
* In the sitebar the widget title should pick up the primary colour set under Customizer > Colors ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-sacha/inc/child-color-patterns.php#L34-L46))
* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-sacha/inc/child-typography.php#L43-L48))
![image](https://user-images.githubusercontent.com/177561/143299672-c52a20b4-c5bd-4b63-869c-bd60135bd5ac.png)
* In the footer, the widget titles should not have the borders to the left and right:
* In the footer, if the background colour is set to 'default' under Customizer > Colors, the widget titles should pick up the primary colour ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-sacha/sass/style.scss#L487-L490))
* ![image](https://user-images.githubusercontent.com/177561/143299877-0bccf3de-b64d-4b59-aa41-093233dd7e06.png)
* In the footer, if the background colour is set to custom under Customizer > Colors the widget titles should be white on darker backgrounds, and black on lighter backgrounds ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-sacha/inc/child-color-patterns.php#L91-L94))
![image](https://user-images.githubusercontent.com/177561/143300339-4e418f7a-a916-4b08-979b-881317f4ee54.png)


**Newspack Scott**

* The sidebar widget title should only be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-typography.php#L42))
![image](https://user-images.githubusercontent.com/177561/143300999-463b24ba-9f80-4204-b898-c6829964de36.png)
* The footer widget title should also be uppercase when the `Use all-caps for accent text` option is selected under the Customizer > Typography panel ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-typography.php#L44-L46))
![image](https://user-images.githubusercontent.com/177561/143300647-b3c1b0eb-0fe2-4391-bcb7-1495c5b21434.png)
* In the footer, if the background colour is set to a darker colour under Customizer > Colors the widget titles should be white ([ref](https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-color-patterns.php#L101-L105))
![image](https://user-images.githubusercontent.com/177561/143301098-e7f418f4-c637-4908-be02-f5c886b74fa0.png)

Again, thank for diving into this! Please let me know if you have any questions about the above!

2021-12-03 19:42 UTC, laurelfulford requested changes
Thanks for taking the time to make these updates, @hawkeye126! 

I did my best to review the diff, though I may have missed some things since there are changes that display that aren't actually included in this commit (just from updating your branch from the theme's updates).

If you have any questions at all, please let me know! Again, I also totally understand if this is a lot -- it's a confusing theme, and I've definitely gone through the same convoluted testing with my own commits, since there are so many weird cases you need to check for!

2021-12-03 19:42 UTC, laurelfulford commented on newspack-theme/inc/color-patterns.php
> +				.site-footer .widgettitle,
There's an extra comma here:

```suggestion
				.site-footer .widget-title,
				.site-footer .widgettitle,
```

2021-12-14 00:37 UTC, hawkeye126 commented on newspack-joseph/inc/child-typography.php
> +			.widgettitle,
Resolved here [707e90a](https://github.com/Automattic/newspack-theme/pull/1532/commits/707e90aae17aff3e05b200f205f6f9dd5bd6cc6c)

2021-12-14 00:45 UTC, hawkeye126 commented on newspack-joseph/inc/child-typography.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolved here https://github.com/Automattic/newspack-theme/pull/1532/commits/2eb71118cda3e5745992b4d22f27c05611fde7d7

2021-12-14 00:47 UTC, hawkeye126 commented on newspack-joseph/inc/child-typography.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolved here https://github.com/Automattic/newspack-theme/pull/1532/commits/5c8175c7d24fa8d368f6cd088321016ca65bf63f

2021-12-14 00:47 UTC, hawkeye126 commented on newspack-joseph/sass/style.scss
> +.widgettitle {
Resolved here [5c8175c](https://github.com/Automattic/newspack-theme/pull/1532/commits/5c8175c7d24fa8d368f6cd088321016ca65bf63f)

2021-12-14 00:47 UTC, hawkeye126 commented on newspack-joseph/sass/style.scss
> +.widgettitle:not( .widget-title )::before,
Resolved here [5c8175c](https://github.com/Automattic/newspack-theme/pull/1532/commits/5c8175c7d24fa8d368f6cd088321016ca65bf63f)

2021-12-14 00:47 UTC, hawkeye126 commented on newspack-joseph/sass/style.scss
> +.author-bio .widgettitle {
Resolved here [5c8175c](https://github.com/Automattic/newspack-theme/pull/1532/commits/5c8175c7d24fa8d368f6cd088321016ca65bf63f)

2021-12-14 00:48 UTC, hawkeye126 commented on newspack-joseph/sass/style-editor.scss
> +.widgettitle {
Resolved here https://github.com/Automattic/newspack-theme/pull/1532/commits/f464f1de2c7722275c6d64e1cff9de4485c41a91

2021-12-14 00:52 UTC, hawkeye126 commented on newspack-nelson/inc/child-typography.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolve here [b040c930][https://github.com/Automattic/newspack-theme/pull/1532/commits/b040c93054a2c2bab7175e5601302c324a4935e7]

2021-12-14 00:53 UTC, hawkeye126 commented on newspack-nelson/sass/style.scss
> +.wp-block-columns .wp-block-column > .widgettitle,
Resolved here 579c04fa

2021-12-14 00:57 UTC, hawkeye126 commented on newspack-sacha/inc/child-color-patterns.php
> +		.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolved here b0de3ae6

2021-12-14 00:57 UTC, hawkeye126 commented on newspack-sacha/inc/child-typography.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolved here 6c0f9a33

2021-12-14 00:58 UTC, hawkeye126 commented on newspack-sacha/sass/style-editor.scss
> +.widgettitle,
Resolved here 5827df1b

2021-12-14 01:00 UTC, hawkeye126 commented on newspack-sacha/sass/style.scss
> +.widgettitle,
Resolved here 942bd624, please ignore 8aac9fde

2021-12-14 01:05 UTC, hawkeye126 commented on newspack-sacha/sass/style.scss
> +	.widgettitle,
Resolved here fa68423

2021-12-14 01:06 UTC, hawkeye126 commented on newspack-sacha/sass/style.scss
> +	.widgettitle, {
Resolved here ecc6842c

2021-12-14 01:13 UTC, hawkeye126 commented on newspack-scott/inc/child-color-patterns.php
> +		.widgettitle:not(.widget-title):before,
Resolved here de5112a9

2021-12-14 01:18 UTC, hawkeye126 commented on newspack-scott/inc/child-color-patterns.php
> +		.mobile-sidebar .widgettitle {
Resolved here f7ed704

2021-12-14 01:19 UTC, hawkeye126 commented on newspack-scott/inc/child-color-patterns.php
> +		.mobile-sidebar .widgetitle::before {
Resolved here 52b092a7

2021-12-14 01:20 UTC, hawkeye126 commented on newspack-scott/inc/child-color-patterns.php
>  			.site-footer .article-section-title::before {
Resolved here 3ac913c2

2021-12-14 01:21 UTC, hawkeye126 commented on newspack-scott/inc/child-color-patterns.php
> +		.block-editor-block-list__layout .block-editor-block-list__block.widgettitle:before,
Resolved here 32224247

2021-12-14 01:24 UTC, hawkeye126 commented on newspack-joseph/sass/style.scss
> +.widgettitle:not( .widget-title ),
Resolved here 5c8175c

2021-12-14 01:25 UTC, hawkeye126 commented on newspack-scott/inc/child-typography.php
>  			.article-section-title,
Resolved here facd5ed2

2021-12-14 01:27 UTC, hawkeye126 commented on newspack-scott/inc/child-typography.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle,
Resolved here 73e2ef93

2021-12-14 01:28 UTC, hawkeye126 commented on newspack-scott/sass/style-editor.scss
> +.widgettitle,
Resolved here a37e812a

2021-12-14 01:28 UTC, hawkeye126 commented on newspack-scott/sass/style.scss
>  .article-section-title,
Resolved here 27486889

2021-12-14 01:29 UTC, hawkeye126 commented on newspack-scott/sass/style.scss
> +.wp-block-columns .wp-block-column > .widgettitle,
Resolved here 3249b214

2021-12-14 01:30 UTC, hawkeye126 commented on newspack-scott/sass/style.scss
> +.author-bio .widgettitle {
Resolved here 8b4633ee

2021-12-14 01:31 UTC, hawkeye126 commented on newspack-scott/sass/style.scss
> +	.widgettitle {
Resolved here 00c8e45a

2021-12-14 01:32 UTC, hawkeye126 commented on newspack-theme/inc/color-patterns.php
>  				.mobile-sidebar .article-section-title {
Resolved here 585dd8da

2021-12-14 01:33 UTC, hawkeye126 commented on newspack-theme/inc/color-patterns.php
>  					.site-footer .article-section-title {
Resolved here 646ad272

2021-12-14 01:33 UTC, hawkeye126 commented on newspack-theme/inc/color-patterns.php
>  					.site-footer .article-section-title {
Resolved here bfc2d4bf

2021-12-14 01:34 UTC, hawkeye126 commented on newspack-theme/inc/color-patterns.php
> +			.block-editor-block-list__layout .block-editor-block-list__block.widgettitle {
Resolved here d162589a

2021-12-14 01:34 UTC, hawkeye126 commented on newspack-theme/inc/typography.php
> +				.widgettitle,
Resolved here 14518429

2021-12-14 01:35 UTC, hawkeye126 commented on newspack-theme/inc/typography.php
>  				.block-editor-block-list__layout .block-editor-block-list__block .article-section-title {
Resolved here 29429181

2021-12-14 01:35 UTC, hawkeye126 commented on newspack-theme/sass/blocks/_blocks.scss
> +		&.widgettitle + div.wpnbha {
Resolved here 658877b6

2021-12-14 01:38 UTC, hawkeye126 commented on newspack-theme/sass/site/secondary/_widgets.scss
> +
Thanks for the clarification @laurelfulford, I have removed the style here 658877b6

2021-12-14 01:39 UTC, hawkeye126 commented on newspack-theme/sass/style-editor-base.scss
>  	.article-section-title {
Resolved here b2361787

2021-12-14 01:40 UTC, hawkeye126 commented on newspack-theme/sass/styles/style-default/style-default-editor.scss
>  .article-section-title {
Resolved here 614b6c8c

2021-12-14 01:41 UTC, hawkeye126 commented on newspack-theme/sass/styles/style-default/style-default.scss
> +.widgettitle,
Resolved here 64808313

2021-12-14 01:41 UTC, hawkeye126 commented on newspack-theme/sass/styles/style-default/style-default.scss
> +.wp-block-columns .wp-block-column > .widgettitle,
Resolved here 5169a736

2021-12-14 01:42 UTC, hawkeye126 commented on newspack-theme/sass/typography/_headings.scss
> +.widgettitle {
Resolved here ed027f03

2021-12-14 01:44 UTC, hawkeye126 commented on newspack-theme/inc/color-patterns.php
> +				.site-footer .widgettitle,
Resolved here b58425d8

2021-12-14 01:47 UTC, hawkeye126 commented
@laurelfulford Thanks for the review and explanations - it's very helpful 💯  !  I have addressed everything (I think anyway) and am ready for another review.  Sorry for the amount of commits, I broke out the fixes to hopefully make it easier on you to review.  If you'd like me to squash them and do some branch cleanup please let me know.

2021-12-22 00:02 UTC, hawkeye126 commented
@laurelfulford I did some branch cleanup to reduce commits and better comply with the contribution guidelines.  Please let me know if you'd like to use that branch, I will update the PR to be against the Automattic repo (right now it's against my fork).  Thanks!

https://github.com/hawkeye126/newspack-theme/pull/12

2022-01-20 00:32 UTC, laurelfulford commented
Thanks @hawkeye126! Apologies for my really late follow up here -- I took some time off for the holidays, and then had to tackle some WordPress 5.9 testing before getting back into things! :) 

> I did some branch cleanup to reduce commits and better comply with the contribution guidelines. Please let me know if you'd like to use that branch, I will update the PR to be against the Automattic repo (right now it's against my fork).

That would be amazing if it's not too much trouble! 🙌 Thank you!

2022-01-21 21:16 UTC, hawkeye126 commented
@laurelfulford here's the updated PR, please let me know if there is anything more I can address.  https://github.com/Automattic/newspack-theme/pull/1678

2022-01-24 20:40 UTC, laurelfulford commented
Awesome, thanks @9ete! 🙌 I'm going to close this one for now and will give feedback in the new PR, but we can reopen this if needed for any reason!

2022-01-24 20:40 UTC, closed without merging