Update es_ES.po
Automattic/newspack-theme pull request #1579
Opened 2021-11-13 11:55 UTC by SergioRodriguezSanchez

Suggestion of spanish translation for the byline if the post have two or more author. ' and ' to ' y '.

### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request: Update translation in spanish for more than one author.

Closes # .

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

2021-11-16 03:33 UTC, laurelfulford requested changes
Thanks for submitting this fix, @SergioRodriguezSanchez -- great catch!

It looks like a spot for this translation already exists in the es_ES.po file, it just has an empty string for the translation -- I've added a note for where that is! 

Also, to have the translation work correctly, we'll need to [generate a new es_ES.mo file](https://stackoverflow.com/questions/4499622/how-can-i-create-an-mo-file-for-wordpress) from your new .po file -- do you have ability to do that? If not, I'm happy to take care of that step and loop in another member of the team to review. 

Just let me know if you have any questions at all -- thanks again!

2021-11-16 03:33 UTC, laurelfulford commented on newspack-theme/languages/es_ES.po
> +#: inc/template-tags.php:121
The `" and "` string already exists further up the file, [here](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/languages/es_ES.po#L974-L977), so there's no need to add the file path and msgid again, only the translation needs to be added on line [977](https://github.com/Automattic/newspack-theme/blob/master/newspack-theme/languages/es_ES.po#L977).

2021-11-16 14:30 UTC, SergioRodriguezSanchez commented on newspack-theme/languages/es_ES.po
> +#: inc/template-tags.php:121
Hi @laurelfulford thanks for the review. It is already changed in line 977 and deleted the previous one, as you requested. If you could generate the 'mo' file will be great as I am not used to do that. Thanks a lot!

2021-11-18 01:56 UTC, laurelfulford approved these changes
Thank you, @SergioRodriguezSanchez - this looks good! 👍 

I'll approve and merge this change, and then follow up with a separate PR to update the es_ES.mo file.

2021-11-18 02:00 UTC, merged

2021-11-21 14:40 UTC, SergioRodriguezSanchez commented
> Thank you, @SergioRodriguezSanchez - this looks good! 👍
> 
> I'll approve and merge this change, and then follow up with a separate PR to update the es_ES.mo file.

Thank you so much!