fix: extend/duplicate .widget-title and .accent-header styles (#1470)
Automattic/newspack-theme pull request #1678
Opened 2022-01-21 21:13 UTC by hawkeye126

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-01-26 00:34 UTC, laurelfulford requested changes
Thanks so much again for your hard work on this PR, @9ete!

We're well into the silly nitpicky weeds with this feedback -- I just found some cases weren't quite acting right, but a ton of the original feedack has been addressed. For the most part I included the feedback in comments directly in the code, but included a bit more below to address an issue that needs to be tweaked in files that haven't been changed yet.

If you have any questions at all about any of this, please let me know!

**For Newspack Katharine:**

The sidebar `.widgettitle` isn't picking up the correct styles -- editing these files should fix!

![image](https://user-images.githubusercontent.com/177561/151080430-f1e2a947-a156-4f44-ba8a-94de01396e1b.png)


newspack-katharine/inc/child-color-patterns.php
*  `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L35-L45
* `#secondary .widgettitle::before` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L53-L61

newspack-katharine/inc/child-color-typography.php
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43

newspack-katharine/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/sass/style.scss#L51-L65

2022-01-26 00:34 UTC, laurelfulford commented on newspack-nelson/inc/child-typography.php
> +			.widgettitle,
This should target the sidebar specifically, like: 

```suggestion
			#secondary .widgettitle,
```

... since the uppercase styles are not applied to widget areas like the slide-out sidebar, or when widgets appear in the mobile menu.

2022-01-26 00:34 UTC, laurelfulford commented on newspack-nelson/sass/style-editor.scss
> +.widgettitle,
The `.widgettitle` shouldn't be needed here, because the class shouldn't appear in the block editor: 

```suggestion
```

2022-01-26 00:34 UTC, laurelfulford commented on newspack-nelson/sass/style.scss
> +.widgettitle,
These specific styles are only needed on the `.widgettitle` class in the sidebar:

```suggestion
#secondary .widgettitle,
```

2022-01-26 00:34 UTC, laurelfulford commented on newspack-sacha/inc/child-typography.php
> +			.widgettitle,
This should just be applied to when the `.widgettitle` class appears in the sidebar:

```suggestion
			#secondary .widgettitle,
```

2022-01-26 00:34 UTC, laurelfulford commented on newspack-sacha/sass/style.scss
> +.widgettitle,
This should just apply when the `.widgettitle` class appears in the sidebar:

```suggestion
#secondary .widgettitle,
```

2022-01-26 00:34 UTC, laurelfulford commented on newspack-sacha/sass/style.scss
> +.widgettitle,
The borders should just be applied to the `.widgettitle` class when it appears in the sidebar:

```suggestion
#secondary .widgettitle,
```

2022-02-05 18:02 UTC, 9ete commented
@laurelfulford all issues resolved, ready for re-review.

2022-02-08 23:54 UTC, laurelfulford requested changes
Thanks @9ete! It's down to just a couple more things now, some of which I missed the last time through! 

I added some comments in the code, and below -- the changes for Newspack Katharine are copied from the last review, but the changes for Newspack Scott underneath that I missed the last time through -- I think I missed testing it. Apologies! 

Just let me know if you have any questions at all -- thank you!

**For Newspack Katharine:**

The sidebar `.widgettitle` isn't picking up the correct styles -- editing these files should fix!

![image](https://user-images.githubusercontent.com/177561/151080430-f1e2a947-a156-4f44-ba8a-94de01396e1b.png)


newspack-katharine/inc/child-color-patterns.php
*  `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L35-L45
* `#secondary .widgettitle::before` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-color-patterns.php#L53-L61

newspack-katharine/inc/child-color-typography.php
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/inc/child-typography.php#L33-L43

newspack-katharine/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-katharine/sass/style.scss#L51-L65


**For Newspack Scott**

The widget titles aren't quite picking up the correct case in the sidebar, or colour and case in the footer -- the following tweaks should fix! 

![image](https://user-images.githubusercontent.com/177561/153092815-b2c4e527-7bb7-4337-9702-e4a320d61160.png)

newspack-scott/inc/child-color-patterns.php
* `#colophon .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-color-patterns.php#L101-L105

newspack-scott/inc/child-typography.php
* `#secondary .widgettitle` and `#colophon .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/inc/child-typography.php#L39-L46

newspack-scott/sass/style.scss
* `#secondary .widgettitle` should be added to this style: https://github.com/Automattic/newspack-theme/blob/master/newspack-scott/sass/style.scss#L61-L63

2022-02-08 23:54 UTC, laurelfulford commented on newspack-sacha/inc/child-color-patterns.php
> +		.widgettitle,
This should be targeted to the sidebar (as well as the footer below) so it's not picked up by any other widget spaces:
```suggestion
		#secondary .widgettitle,
```

2022-02-08 23:54 UTC, laurelfulford commented on newspack-sacha/sass/style.scss
> +#secondary .widgettitle,
Currently the styles in this section (starting at line 73) look like:
```
// Accent headers
.accent-header,
#secondary .widgettitle,
.article-section-title,
.cat-links {
	color: $color__primary;
}

.accent-header,
#secondary .widgettitle,
div.wpnbha .article-section-title,
.cat-links {
	font-size: $font__size-xs;
	margin-bottom: $size__spacing-unit;
	text-align: center;
}
```

They way we broke them up isn't exactly necessary, and the `$font__size-xs;` is making the sidebar widget titles extra small: 

![image](https://user-images.githubusercontent.com/177561/153095235-3ca999f8-0998-45eb-a2b7-feeda3f9344d.png)

Rejigging the current styles a bit should help fix the font sizing -- below I combined all four selectors to apply the colour, margin and text-alignment, and then removed `#secondary .widgettitle` where the font size has been applied: 


```
.accent-header,
#secondary .widgettitle,
.article-section-title,
.cat-links {
	color: $color__primary;
	margin-bottom: $size__spacing-unit;
	text-align: center;
}

.accent-header,
div.wpnbha .article-section-title,
.cat-links {
	font-size: $font__size-xs;
}
```

2022-02-12 19:14 UTC, 9ete commented
@laurelfulford thanks for the feedback, I've addressed all issues, should be good to go now!

2022-02-18 01:53 UTC, laurelfulford requested changes
Thank you, @9ete! 

I went through this with a fine toothed comb one more time, and only spotted one issue with a formatting fix that was made earlier on (instead of re-adding a line-break, a bit of code was removed). Other than that, everything looks fantastic! 🎉 

Thank you again for your hard work on this. Once that bit of code is back, this will be ready to merge!

2022-02-18 01:53 UTC, laurelfulford commented on newspack-nelson/inc/child-typography.php
> -			.block-editor-block-list__layout .block-editor-block-list__block .article-section-title,
I think `.block-editor-block-list__layout .block-editor-block-list__block .article-section-title,` here was accidentally removed as part of a formatting fix -- [in a previous run though](https://github.com/Automattic/newspack-theme/pull/1678/files/cc33f078c38a922f8b03dcb5842710e830297930#diff-4f35070fcc5427e4d0f46f3d0a3d8d32a1f6b3ff4a1f308c54e0f56c4ec143c0), I'd commented that a line break had been removed when it shouldn't be between this selector and the one above it, but I think the code comparison I included made it look like the whole bit should be removed! 

If you can please re-add this, I think this PR is ready to go!

2022-02-18 20:34 UTC, 9ete commented on newspack-nelson/inc/child-typography.php
> -			.block-editor-block-list__layout .block-editor-block-list__block .article-section-title,
@laurelfulford done!

2022-02-19 18:45 UTC, laurelfulford approved these changes
Everything looks good -- thanks again so much for your help and patience with this PR, @9ete! 🎉

2022-02-19 18:48 UTC, merged