fix: remove ads custom media queries
Automattic/newspack-theme pull request #1717
Opened 2022-02-24 19:14 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

With the recent implementation of #1699, this custom media query control of legacy SCAIP ads is preventing wider units to be displayed.

I couldn't identify a reason to keep this filter as it is only being applied to legacy (widget) SCAIP ads and its purpose is not clear to me. The native implementation of media queries should handle the different viewports without the need for this customization.

### How to test the changes in this Pull Request:

1. On the master branch make sure you have SCAIP in legacy mode, AMP active and AMP Plus off
2. Add a valid ad unit to the first SCAIP position containing the following sizes: `300x250`, `728x90`, `970x250`
3. Visit a post with a wide template and observe you are not able to render the `970x250` size
4. Check out this branch, refresh the post page and confirm you are able to render the `970x250` size

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-02-24 23:22 UTC, dkoo requested changes
I dug through the `blame` for this function and found this context: https://github.com/Automattic/newspack-ads/pull/31

I think now that we have full-viewport-width SCAIP ads on one-column and one-column-wide templates, plus true responsive ads in SCAIP placements, this works well for those templates. However, does it also work for the default template? I couldn't verify because I couldn't get a 970x250 or 728x90 ad unit to actually render in my test site, but I want to make sure that the responsive ads are intelligent enough to render an appropriate size based on the ad's container, not just the viewport.

2022-02-24 23:54 UTC, dkoo approved these changes
Update: I was able to get this working on a fresh site, and the correct size rendered in the default/one-column (729x90) and one-column-wide (970x250) templates.

2022-02-25 14:21 UTC, miguelpeixe commented
> I was able to get this working on a fresh site, and the correct size rendered in the default/one-column (729x90) and one-column-wide (970x250) templates.

This was probably by chance. We are not taking the container width into account for determining which ad should be rendered. This can be achieved by using the recently implemented `template` targeting key values to target creatives for wide templates.

2022-02-25 16:43 UTC, miguelpeixe commented
The `template` targeting key has already been tackled at https://github.com/Automattic/newspack-ads/pull/297

2022-02-25 17:19 UTC, dkoo approved these changes

2022-02-25 17:43 UTC, merged