fix: update approach to remove space with above footer ad
Automattic/newspack-theme pull request #1746
Opened 2022-03-28 19:16 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the approach to removing the gap between the above footer ad space when it has a background, and the footer. 

Originally this was done by adding a negative margin to the ad space; I believe that stopped working as expected when the `overflow: hidden` was moved in #1254-- now, the negative margin causes the ad to get cut off. 

This PR checks for an ad in that location, and if there is one, adds a CSS that's then used to remove the margin above the footer. 

This approach seemed the least disruptive (it doesn't try to move the ad; it doesn't remove the margin on top of the footer outright), but I'm open to feedback if it seems like it's over-complicating things. I also may not have used the best approach for checking for the Above Footer ad space!

Closes #1743

### How to test the changes in this Pull Request:

1. Navigate to Customizer > Colors, and add a background colour to your ads.
2. Add an ad to the 'Above Footer' location.
3. View on the front end -- there is a gap between your ad background colour, and part of your ad is getting cut off: 

![image](https://user-images.githubusercontent.com/177561/160470358-75a7e51a-0c71-4dc9-b7aa-c1788a0b214e.png)

5. Apply the PR and run `npm run build`.
6. Confirm that the ad is no longer cut off, and there is no longer a gap between the ad background and the footer. 

![image](https://user-images.githubusercontent.com/177561/160470154-2fb95720-f804-4325-9654-3b8c8ee70d16.png)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-03-29 20:48 UTC, miguelpeixe requested changes
Working as described! One suggestion below:

2022-03-29 20:48 UTC, miguelpeixe commented on newspack-theme/inc/template-functions.php
> +	$above_footer_ad = get_option( '_newspack_ads_placement_global_above_footer' );
```suggestion
	$above_footer_ad      = method_exists( 'Newspack_Ads\Placements', 'can_display_ad_unit' ) && \Newspack_Ads\Placements::can_display_ad_unit( 'global_above_footer' );
```

The placements system provides a public method with more advanced checks to verify if the placement will render an ad unit which I believe is more suitable.

2022-03-29 20:48 UTC, miguelpeixe commented on newspack-theme/inc/template-functions.php
> +		if ( str_contains( $above_footer_ad, '"enabled":true' ) ) {
```suggestion
		if ( true === $above_footer_ad ) {
```

The suggested method above returns a boolean value.

2022-03-30 16:18 UTC, laurelfulford commented on newspack-theme/inc/template-functions.php
> +	$above_footer_ad = get_option( '_newspack_ads_placement_global_above_footer' );
🙌 Awesome, thanks Miguel! I made this update in [a2e5486](https://github.com/Automattic/newspack-theme/pull/1746/commits/a2e548679d56567b2ca57d2f2880abb2490dbcb8).

2022-03-30 16:24 UTC, laurelfulford commented
Woohoo! Thanks for the review! 🙌

2022-03-30 16:25 UTC, merged