Add checkbox style
Automattic/newspack-theme pull request #1840
Opened 2022-06-07 12:57 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The theme currently doesn't have custom style for checkboxes, this PR adds a simple checkbox style.

Note: I saw WooCommerce has some custom styles already (#ship-to-different-address) but I wasn't able to find out how to test it

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Navigate to a screen that has a checkbox (e.g. yoururl.com/product/donate/)
3. Update button's background colour and play with text colour contrast (black/white)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-06-08 21:22 UTC, laurelfulford requested changes
Overall this worked well in my testing! The colours were picked up as expected, and the contrast worked well. 

The only issue I can see with this change is that it changes the `input['checkbox']` from being inline to being block with `display: grid`. We can fix where this affects things in the theme, like the comment form:

![image](https://user-images.githubusercontent.com/177561/172719078-d803efaf-4154-4d23-8213-9817c99ff803.png)

... but it will also affect markup from any plugins sites use, which could be a pain to correct. Off the top of my head, MC4WP "assumes" that the checkbox is inline so we would see some wider varied breakage from that ([example at the bottom of this page](https://wisconsinwatch.org/)).

Switching the checkbox to `display: inline-grid` seems to help in my testing -- will that cause other issues I'm not thinking of?

> Note: I saw WooCommerce has some custom styles already (#ship-to-different-address) but I wasn't able to find out how to test it

This appears on the checkout page -- in my testing, it looked and acted exactly the same with and without this PR applied: 

![image](https://user-images.githubusercontent.com/177561/172717657-db9e6784-b2eb-48e7-aa97-02f23f4d9795.png)
![image](https://user-images.githubusercontent.com/177561/172717686-b0b556a7-75d7-45e9-89ce-bec6e8d69429.png)

2022-06-09 19:08 UTC, laurelfulford commented on newspack-theme/inc/template-functions.php
> +		return 'black';
Apologies, I missed this the first time though! 

The output of this function is also used to figure out whether to switch the primary or secondary colour to a medium grey when they don't have sufficient contrast against white: 

https://github.com/Automattic/newspack-theme/blob/984644407faa7b30acc38752f2cfbac971cb4f3b/newspack-theme/inc/template-functions.php#L590

`newspack_color_with_contrast()` should also be updated to check for `black`.

2022-06-10 08:37 UTC, thomasguillot commented on newspack-theme/inc/template-functions.php
> +		return 'black';
Note: To find the closest match, I used this brilliant tool: https://stubbart.com/computer_consulting/color_themes/color_closest.html

2022-06-10 23:43 UTC, laurelfulford approved these changes
This looks good, @thomasguillot!

> which is more generic and offers a slightly better contrast

Iiiii have to ask about this because I feel like I'm missing something 😅  `dimgray` comes back as `#696969` for me, or a contrast ratio of 5.48:1 against white, compared to 6.89:1 with `#5a5a5a` -- so I think the contrast is less? It's not a problem since both pass WCAG AA, I'm just wondering if I've misunderstood this bit -- thanks!

(Totally good to merge, though!)

2022-06-11 20:26 UTC, thomasguillot commented
> Iiiii have to ask about this because I feel like I'm missing something 😅 `dimgray` comes back as `#696969` for me, or a contrast ratio of 5.48:1 against white, compared to 6.89:1 with `#5a5a5a` -- so I think the contrast is less? It's not a problem since both pass WCAG AA, I'm just wondering if I've misunderstood this bit -- thanks!

🤦 

My bad! You're totally right.

2022-06-11 20:27 UTC, merged