fix: correct issues with users and guest authors sharing IDs
Automattic/newspack-theme pull request #2008
Opened 2022-12-21 19:45 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes a couple issues that arise when a regular user and a CoAuthors Plus guest user share the same ID:
* The 'regular user' ends up with the incorrect avatar ([caused by an old fix to make sure CoAuthors didn't pick up post featured images as a fallback](https://github.com/Automattic/newspack-theme/pull/569))
* The guest user ends up with the wrong name/description on the Author Archives page.

This PR also fixes an issue where guest author information was not displaying on the archive pages. 

Closes 1200133283606042/1203581044315819

### How to test the changes in this Pull Request:

1. Start with a test site where at least one WP User shares an ID with a CoAuthors Plus Guest Author. If you don't already have a site with this, you can recreate it by:
   * Spin up a new Newspack site (opting NOT to install the demo content)
   * Add two Guest Authors, both with names, bios, but no avatars for now. To make testing easier, prefix the bios with the user name.  
   * Checking the ID of the first Guest Author; and add enough WP Users to get up to that ID number -- for me, it was ID 13. Make sure at least this 'ID twin' WP User has a bio that starts with their user name.
2.  Set up a few posts:
    * Posts just by your "ID twin" Guest Author
    * Posts just by your "ID twin" WP User
    * Posts by both together
    * Posts by your "ID twin" Guest Author and another random user
    * Posts by the Guest Author that doesn't have an ID twin. 
3. Make sure your "ID Twin" WP User has an avatar (either through Gravatar or Simple Avatars), but your "ID Twin" Guest Author does not. 
4. Visit the post by the "ID twin" WP User; note that rather than using its avatar, it's using the 'fallback' option -- this is because it's picking up the Guest Author's avatar:

_WP User's settings:_ 
![image](https://user-images.githubusercontent.com/177561/208987864-891c8b1d-c0c3-4d73-aaee-c34669e4dea8.png)

_WP User's byline:_
![image](https://user-images.githubusercontent.com/177561/208987672-72967e1a-7773-4180-92c1-f3722d83c46f.png)
  
6. Visit the archive of the "ID twin" guest author; note that it's using the WP User's name and description.

_Note the URL points to guest author 'Jane Doe' but the name/description does not -- the posts should match the right person though:_
![image](https://user-images.githubusercontent.com/177561/208987989-302bf201-f700-40b3-8f8c-ec96fc0572d4.png)

7. Visit the regular Guest Author that doesn't have an "ID twin"; notice that its not displaying any information:

![image](https://user-images.githubusercontent.com/177561/208988327-b154669d-b8a9-46ce-ac25-60c29f5f1ac0.png)

9. Apply the PR.
10. Visit the post by the "ID twin" WP User; confirm that its using the correct avatar.

![image](https://user-images.githubusercontent.com/177561/208989702-33aa57e2-c261-4ee3-972e-f463b5c2049d.png)

11. Visit the archive of the "ID twin" guest author, and confirm that it's displaying the correct name and description.

![image](https://user-images.githubusercontent.com/177561/208989754-f5e6c4d6-7950-4903-87e4-e6617c09ced3.png)

12. Visit the regular Guest Author that doesn't have an "ID twin" and confirm their information is displaying:

![image](https://user-images.githubusercontent.com/177561/208989609-73c3ebdf-3503-4a45-a92b-80bcf6badefe.png)

13. Test adding/removing avatars from the Guest Authors (both with ID twins and without), and confirm that they correctly fall back to the placeholder image set under Settings > Discussion, and not featured images. 

14. Swap to Newspack Sacha, and comfirm that the Author Bios at the bottom of posts are using the correct images as well -- this is the only child theme that has a unique template part for this section.

(Note: the avatar issue still needs to be addressed separately in the blocks). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-12-21 22:28 UTC, leogermani requested changes
I ran all the tests and everything you describe works well.

If we dig, there are still some bugs on how CAP handles this, but it's not our fault and I dont see it interfering with the site front end... 

we can dig more later, but I think the changes look good and the code is easier to read.

I left one comment with a test that looks ambiguous to me. I don't know if you want that check to pass in both cases or if you are trying to filter that condition only to guest authors. (if you are, it's not working)

2022-12-21 22:28 UTC, leogermani commented on newspack-theme/archive.php
> +				if ( is_author() && 'guest-author' === get_post_type( $queried->ID ) ) {
This check is ambiguous, it will return `true` both for the real WP user archive page and for the Guest Author archive page.

Is that the intention? Maybe we could be more explicit here, like 

```
if ( is_author() && $queried instanceof WP_User ) {
```
if we want to check if it's a real user archive.

If we want to check if it's a guest author archive:

```
if ( is_author() && $queried instanceof StdClass && isset($queried->type) && 'guest-author' ===  $queried->type) {
```
(there might be an easier way for the latter, but that's the idea)

2022-12-21 22:28 UTC, leogermani commented on newspack-theme/archive.php
> +				elseif ( is_author() && 'guest-author' === get_post_type( $queried->ID ) && '' !== $queried->description ) :
same as above

2022-12-21 22:41 UTC, laurelfulford commented on newspack-theme/archive.php
> +				if ( is_author() && 'guest-author' === get_post_type( $queried->ID ) ) {
🤦‍♀️ Thanks @leogermani! 

This was to "fix" the odd issue I saw with the archive title and description being incorrect or not displaying at all, but I can't recreate it now - that's probably why it seemed to work for me! 

It did seem very strange to me that the Guest Author information hadn't been working all this time and wasn't reported -- in reality I think it was an odd blip that happened on my test site and went away on its own.

I'm going to remove this and the description code you flagged below, and do a little more testing myself, then update this PR 🙂

2022-12-22 01:00 UTC, laurelfulford commented on newspack-theme/archive.php
> +				if ( is_author() && 'guest-author' === get_post_type( $queried->ID ) ) {
Ok, I've updated the PR to remove the above code for now! 

I was able to recreate the Author Title and Description being wrong by removing all the menus from the site. If this is somehow related to the theme, it _seems_ unrelated to this particular problem, so I'm going to investigate it separately!

2022-12-22 01:01 UTC, laurelfulford commented on newspack-theme/archive.php
> +				elseif ( is_author() && 'guest-author' === get_post_type( $queried->ID ) && '' !== $queried->description ) :
With the above, should be resolved in [2afbbba](https://github.com/Automattic/newspack-theme/pull/2008/commits/2afbbba5ea88bacaf79c4f0fdede01a9274656b3)!

2022-12-22 13:37 UTC, leogermani approved these changes
Tests well in all scenarios for me

2022-12-22 20:07 UTC, laurelfulford commented
Thanks @leogermani! 🙌

2022-12-22 20:07 UTC, merged