feat: add Mastodon icon to the social links menu
Automattic/newspack-theme pull request #2017
Opened 2023-01-11 01:24 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a Mastodon icon to the social links menu, as well as a list of common Mastodon URLs to match to it. 

See 1203536997639429-as-1203401705449116

### How to test the changes in this Pull Request:

1. Add one of the common Mastodon URLs to the social links menu - the URLs include the following, and account links are formatted like https://[mastodon URL]/@[mastodon username]

* counter.social
* fosstodon.org
* gc2.jp
* hachyderm.io
* infosec.exchange
* mas.to
* mastodon.art
* mastodon.cloud
* mastodon.lol
* mastodon.online
* mastodon.social
* mastodon.world
* mstdn.jp
* mstdn.social
* newsie.social
* pawoo.net

2. Note that the menu uses the 'link' icon placeholder for this link

![image](https://user-images.githubusercontent.com/177561/211696064-c1020da5-682f-4cf3-8f91-47a942d9f025.png)

3. Apply the PR.
4. Confirm that the Mastodon icon is now loading:

![image](https://user-images.githubusercontent.com/177561/211696022-c3e41cf4-cbd8-4c27-8c63-67c1df497117.png)

5. Depending where your social links menu is displaying (header or footer), switch the background colour to the opposite contrast to what it is now. So for example, if the icon is showing on a dark blue background, change it to white; if it's on a light grey background change it to something dark. This is just to make sure the icon is picking up the contrasting colour correctly.

The list of common Mastodon URLs comes from this [Jetpack Social Icons PR](https://github.com/Automattic/jetpack/pull/28175/files#diff-569b9a627b3b65759e6e3e44a97e6c34f3f4f1c68c4843dea4080e428005a2a5R440-R453); something else that was done in that PR that we could also consider is adding a filter so the URLs can be added to on a per-site basis. Mastodon is odd in that the URLs it could use are endless; I think it's worthwhile trying to add really common ones to the theme, but if we get requests for more that might be the way to go. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-01-11 09:41 UTC, adekbadek requested changes

2023-01-11 09:41 UTC, adekbadek commented on newspack-theme/classes/class-newspack-svg-icons.php
> +			'#https?:\/\/(www\.)?mastodon\.(\w+)(\.\w+)?#',
This didn't work for me when a `http://mastodon.lol/@user` link was supplied. But it did with this change:

```suggestion
			'mastodon.',
```

(same goes for the line below)

2023-01-11 19:12 UTC, laurelfulford commented on newspack-theme/classes/class-newspack-svg-icons.php
> +			'#https?:\/\/(www\.)?mastodon\.(\w+)(\.\w+)?#',
🤦‍♀️ Thanks @adekbadek! I changed too many things in one go without retesting everything. This should now be resolved in [9a596b6](https://github.com/Automattic/newspack-theme/pull/2017/commits/9a596b69917e7be8ef57e12587b8d50fb53501c7)!

2023-01-12 11:25 UTC, adekbadek approved these changes

2023-01-12 16:34 UTC, laurelfulford commented
🙌

2023-01-12 16:35 UTC, merged