fix: Sacha author bio link
Automattic/newspack-theme pull request #2041
Opened 2023-02-18 18:10 UTC by gamebits

Updates Sacha to use `get_the_author_meta` for the "Read more" link in the author bio; otherwise, the nicename isn't obtained and the link points to `/author/` with no slug.

### All Submissions:

* [X] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Brings Sacha's `author-bio.php` template part in line with the Newspack parent theme.

### How to test the changes in this Pull Request:

1. Activate the Newspack Sacha theme.
2. Publish a post and assign it to any author (say, `newspack`) who has a bio.
3. Ensure the Customizer's "Display Author Bio" option is enabled and "Truncate Author Bio" is disabled.
4. Scroll to the bottom of a single post and click the author's "More by" link. It will point to `https://example.com/author/`
5. Switch to this branch and test again. The link will now go to `https://example.com/author/newspack/`

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you written new tests for your changes, as applicable?
* [X] Have you successfully ran tests with your changes locally?

2023-02-20 19:07 UTC, dkoo requested changes
I'm not able to replicate the bug you're reporting (incorrect author URLs on `master`). But the change doesn't seem to result in any negative consequences, either.

There are a couple of additional instances of `get_author_posts_url( $author->ID, $author->user_nicename ) )` in this file on lines 51 and 61. Do these also need to be updated, or are they working as intended? cc @laurelfulford

2023-02-21 15:37 UTC, leogermani commented on newspack-sacha/template-parts/post/author-bio.php
> +			<a class="author-link" href="<?php echo esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ); ?>" rel="author">
We need to pass the user nicename as the second parameter here. This is used to disambiguate the author when a Guest Author has the same ID of a real user. We can't remove that.

2023-02-22 16:48 UTC, laurelfulford approved these changes
Testing this without Co-Authors Plus activated, I'm able to recreate the issue and confirm that this does fix it -- I added more detail in the code comment, but basically this line is only run when Co-Authors Plus is deactivated, so the nice name shouldn't be needed in this specific case. 

I'm marking this as approved, but tagging @leogermani & @dkoo just in case this still seems incorrect to you!

2023-02-22 16:48 UTC, laurelfulford commented on newspack-sacha/template-parts/post/author-bio.php
> +			<a class="author-link" href="<?php echo esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ); ?>" rel="author">
I think this should actually be okay -- it's inside of an if/else statement checking for Co-Authors Plus, and this specific bit is only run if Co-Authors Plus is not enabled (that's also the specific case where this happens, the link works okay when that plugin is activated). 

It's repetitive, but each case (with and without Co-Authors Plus) has a case where the bio is truncated, and a case where it is not -- in Newspack Sacha, [the case where the bio is truncated matches this](https://github.com/Automattic/newspack-theme/blob/master/newspack-sacha/template-parts/post/author-bio.php#L112), and the link works.

2023-02-22 16:59 UTC, leogermani approved these changes

2023-02-22 16:59 UTC, leogermani commented on newspack-sacha/template-parts/post/author-bio.php
> +			<a class="author-link" href="<?php echo esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ); ?>" rel="author">
ok! Thanks for diving into it!

2023-02-24 20:36 UTC, merged