Fix/more space for my account
Automattic/newspack-theme pull request #2051
Opened 2023-03-02 01:59 UTC by laurelfulford

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adjusts the spacing and header breakpoints when the RAS My Account is visible, to avoid some weird wrapping and crammed spacing when the logo is centred. 

See 203981098043663-as-1203870203438177

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-03-08 22:14 UTC, dkoo requested changes
Most of the combinations I tested worked well and provided enough space for the Sign In/My Account button.

This combination doesn't work so well, but it probably has more elements than a real site would (short header + long horizontal logo + show site title + show site tagline + longish menu + RAS). 

<img width="1212" alt="Screen Shot 2023-03-08 at 2 48 05 PM" src="https://user-images.githubusercontent.com/2230142/223861019-c24250ce-6f94-4f48-ac54-e0ca3b03828a.png">

I did find that adding `flex: 1;` to the `.site-branding` element fixed it in this case.

<img width="1204" alt="Screen Shot 2023-03-08 at 3 03 52 PM" src="https://user-images.githubusercontent.com/2230142/223861076-ecfe9cbb-39a8-4caf-ba6e-ce49dbe19bbe.png">

Also left a few suggestions about the code checking whether RAS exists/is active.

2023-03-14 17:03 UTC, laurelfulford commented
Thanks for reviewing this, @dkoo!

In revisiting this, I'm seeing that it's going to have more of an impact on RAS sites that have already launched than I expected 😬 I'm going to work on your updates, as well as trying to reign things in a bit so they don't affect logos sizes on desktop as much.

2023-03-22 17:52 UTC, laurelfulford commented on newspack-theme/inc/template-functions.php
> +	if ( class_exists( '\Newspack\Reader_Activation' ) ) {
This should be addressed in [cacc4f7](https://github.com/Automattic/newspack-theme/pull/2051/commits/cacc4f72866fa0e83c3a1dc6d7a1c1eed2f0ec0f)!

2023-03-22 17:52 UTC, laurelfulford commented on newspack-theme/inc/template-functions.php
> +		if ( $ras_settings['enabled'] && $ras_settings['enabled_account_link'] ) {
This should be addressed in [cacc4f7](https://github.com/Automattic/newspack-theme/pull/2051/commits/cacc4f72866fa0e83c3a1dc6d7a1c1eed2f0ec0f)!

2023-03-22 17:52 UTC, laurelfulford commented on newspack-theme/inc/logo-resizer.php
> +			if ( $ras_settings['enabled'] && $ras_settings['enabled_account_link'] && ( $header_simplified || $header_center_logo ) ) {
I ended up removing this code from the logo-resizer.php file, so this should be resolved, but for different reasons.

2023-03-22 17:53 UTC, laurelfulford commented on newspack-theme/inc/logo-resizer.php
> +		if ( class_exists( '\Newspack\Reader_Activation' ) ) {
Thanks for these, @dkoo! I ended up removing this code from the logo-resizer.php file, so this should be resolved, but for different reasons.

2023-03-28 15:45 UTC, dkoo approved these changes
New RAS checks and methods look 👍 

The combo I called out before (short header + long horizontal logo + show title + show tagline + RAS My Account button) looks better than before, but differs slightly from the [original style](https://github.com/Automattic/newspack-theme/pull/2051#pullrequestreview-1331180418) in which the title and tagline sit side-by-side. It doesn't look worse now, just different, so I'm approving.

<img width="1219" alt="Screen Shot 2023-03-28 at 9 44 24 AM" src="https://user-images.githubusercontent.com/2230142/228293606-f6396fc0-a2f7-4d2f-8b91-ce3e30bafce6.png">

2024-01-05 14:35 UTC, adekbadek commented
@laurelfulford – what's the status on this one?

2024-01-23 18:24 UTC, laurelfulford commented
@adekbadek thanks for following up on this! I did some more of my own testing, and wasn't entirely confident this wasn't going to cause unexpected outcomes with live site headers 😬 It's been long enough now, I wonder if it'd be best just to tighten up the spacing/reduce the button size a bit, and leave the logo alone (which is where I ran into the most noticeable differences).

2024-03-22 21:39 UTC, laurelfulford commented
I'm going to close this PR and start from scratch -- the spacing could be improved, but messing with the logo sizing at this point is too risky.

2024-03-22 21:39 UTC, closed without merging