Make menu display functions pluggable
Automattic/newspack-theme pull request #2159
Opened 2023-07-11 19:14 UTC by DennisNDean

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Made the functions to display the menus (newspack_primary_menu, newspack_secondary_menu, newspack_tertiary_menu and newspack_social_menu_settings) pluggable so they can be safely overridden in a custom function.

### How to test the changes in this Pull Request:

Example:

**newspack-theme/inc/template-tags.php:599**
```
if ( ! function_exists( 'newspack_tertiary_menu' ) ) :
	/**
	 * Displays tertiary menu; created a function to reduce duplication.
	 */
	function newspack_tertiary_menu() {
		if ( ! has_nav_menu( 'tertiary-menu' ) ) {
			return;
		}

		// Only set a toolbar-target attributes if the tertiary menu container exists in the header - if not subpage header.
		$toolbar_attributes = '';
		if ( false === get_theme_mod( 'header_sub_simplified', false ) || is_front_page() ) {
			$toolbar_attributes = 'toolbar-target="tertiary-nav-contain" toolbar="(min-width: 767px)"';
		}
		?>
			<nav class="tertiary-menu nav3" aria-label="<?php esc_attr_e( 'Tertiary Menu', 'newspack' ); ?>" <?php echo $toolbar_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
				<?php
				wp_nav_menu(
					array(
						'theme_location' => 'tertiary-menu',
						'container'      => false,
						'items_wrap'     => '<ul id="%1$s" class="%2$s">%3$s</ul>',
						'depth'          => 1,
					)
				);
				?>
			</nav>
		<?php
	}
endif;
```	

**in plugin:**
```
if ( ! function_exists( 'newspack_tertiary_menu' ) ) :
	/**
	 * Displays tertiary menu; created a function to reduce duplication.
	 */
	function newspack_tertiary_menu() {
		if ( ! has_nav_menu( 'tertiary-menu' ) ) {
			return;
		}

		// Only set a toolbar-target attributes if the tertiary menu container exists in the header - if not subpage header.
		$toolbar_attributes = '';
		if ( false === get_theme_mod( 'header_sub_simplified', false ) || is_front_page() ) {
			$toolbar_attributes = 'toolbar-target="tertiary-nav-contain" toolbar="(min-width: 767px)"';
		}
		?>
			<nav class="tertiary-menu nav3" aria-label="<?php esc_attr_e( 'Tertiary Menu', 'newspack' ); ?>" <?php echo $toolbar_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
				<?php
				wp_nav_menu(
					array(
						'theme_location' => 'tertiary-menu',
						'container'      => false,
						'items_wrap'     => '<ul id="%1$s" class="%2$s">%3$s</ul>',
						'depth'          => 2, // allow submenu items
					)
				);
				?>
			</nav>
		<?php
	}
endif;	
```
Changing `'depth' => 1` to `'depth' => 2` allows sub-menu items, which can then be styled on the front end.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-07-11 23:36 UTC, dkoo commented
@DennisNDean thanks for the PR! This is in the team's queue for review.

2023-07-14 19:24 UTC, laurelfulford requested changes
Thanks for your contribution, @DennisNDean! This is a nice enhancement of the menu code 🙂 

I found one small issue that I marked inline; once that's fixed, this should be good to go!

2023-07-14 19:34 UTC, DennisNDean commented
Whoops — Thanks for catching that!

2023-07-14 22:57 UTC, laurelfulford approved these changes
Thanks for your speedy fix! 🙌 This looks good to me!

2023-07-14 22:59 UTC, merged