fix: clears woo template cache
Automattic/newspack-theme pull request #2201
Opened 2023-11-08 18:55 UTC by leogermani

Needed after files removed in 498192a4323771803626e5695f60b79c0adaf10e

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

In https://github.com/Automattic/newspack-theme/pull/2191 we removed two Woo templates from the theme.

In sites using persistent cache, Woo would still try to load the templates from the theme and the checkout page would break.

This PR will clear the cache to make sure it doesn't happen

### How to test the changes in this Pull Request:

Here is what you need if you want to test this

1. Make sure memcached is on
2. Checkout a version of the theme before https://github.com/Automattic/newspack-theme/pull/2191
3. Add a product to the cart and visit the checkout page (the regular checkout page, not our modal checkout)
4. Checkout theme on `master`
5. Visit checkout again and confirm the page is blank and there's an error in the log complaining about the missing file
6. Checkout this branch and confirm the Checkout page is back

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-08 22:05 UTC, dkoo requested changes
For some reason I couldn't replicate the bug on a test site despite having memcached running, but I did see this happen on a live site. The cache clear should fix things for other live sites going forward. Just one issue I saw, below.

2023-11-08 22:05 UTC, dkoo commented on newspack-theme/woocommerce/templates.php
> +if ( get_option( 'newspack_theme_woo_templates_version', 0 ) !== $newspack_theme_woo_templates_version ) {
Edge case, but this ends up throwing a fatal if WooCommerce is deactivated unless we check for the existence of the function first:

```suggestion
if ( function_exists( 'wc_clear_template_cache' ) && get_option( 'newspack_theme_woo_templates_version', 0 ) !== $newspack_theme_woo_templates_version ) {
```

2023-11-09 11:11 UTC, leogermani commented on newspack-theme/woocommerce/templates.php
> +if ( get_option( 'newspack_theme_woo_templates_version', 0 ) !== $newspack_theme_woo_templates_version ) {
Good call

2023-11-09 18:33 UTC, dkoo approved these changes

2023-11-09 20:12 UTC, merged