feat: filter JS and print styles enqueuing
Automattic/newspack-theme pull request #2207
Opened 2023-11-23 15:27 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds filters for dequeuing print styles and JS scripts.

### How to test the changes in this Pull Request:

Load a page, observe that print styles (`print.css`) and JS scripts (e.g. `amp-fallback.js`) are loaded as expected

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-24 21:19 UTC, leogermani commented on newspack-theme/functions.php
> +		return;
There are some styles being loaded down below. See lines 471 and 475. Maybe they should be moved?

2023-11-27 08:15 UTC, adekbadek commented on newspack-theme/functions.php
> +		return;
Good catch! Fixed in 702b208cd34bd0804e42d4a3b3d663bbeded137a

2023-11-27 11:46 UTC, leogermani approved these changes

2023-11-27 11:46 UTC, leogermani requested changes
actually we should also add docblocks here

2023-11-30 21:21 UTC, dkoo approved these changes

2023-12-01 08:32 UTC, merged