fix: update dependencies to avoid conflict in WP 6.6
Automattic/newspack-theme pull request #2318
Opened 2024-06-14 23:00 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Refactoring required for changes in https://github.com/Automattic/newspack-scripts/pull/209. Note that this PR will not pass CI tests and should NOT be merged until https://github.com/Automattic/newspack-scripts/pull/209 is released as an NPM package, so this repo can install it as a dependency.

### How to test the changes in this Pull Request:

Follow instructions in https://github.com/Automattic/newspack-scripts/pull/209.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-06-20 18:03 UTC, chickenn00dle requested changes
Thanks for this @dkoo!

I left a few comments where I ran into some issues. In addition I had one other note worth bringing up that is likely unrelated to this PR, but is still worth mentioning:

I noticed a bunch of JS errors in console while smoke testing in customizer. This happen in both `trunk` as well as the updated branches, and for both the current WP and 6.6

![Screenshot 2024-06-20 at 13 18 26](https://github.com/Automattic/newspack-theme/assets/17905991/6830b07a-c8b9-41ee-bd53-115ad176c57f)

2024-06-20 18:03 UTC, chickenn00dle commented on package.json
> +		"release": "npm run build && npm run semantic-release",
Running `npm run release` returns the following output after the build process completes:

```
[newspack-scripts@1.0.0] Unknown script "proxy".
```

2024-06-20 18:03 UTC, chickenn00dle commented on package.json
> +	"scripts": {
There are a bunch of npm scripts included in package.json that are not explicitly mentioned in the testing steps. For example, `npm run format:scss` which right now does seem to format sass files, but exits with an error code 2 and no useful messaging. Are these meant to be removed/cleaned up?

2024-06-20 18:38 UTC, chickenn00dle submitted a review, later dismissed
Whoops. This comment was meant to be posted in the blocks PR 😨

2024-06-20 20:08 UTC, dkoo commented on package.json
> +		"release": "npm run build && npm run semantic-release",
Whoops, this was a holdover from a prior commit. Fixed in 0f2f821c

2024-06-20 20:10 UTC, dkoo commented on package.json
> +		"lint:scss": "newspack-scripts wp-scripts lint-style '**/{src,includes}/**/*.scss' --customSyntax postcss-scss",
You're right—committed your suggested change.

2024-07-30 13:51 UTC, miguelpeixe requested changes

2024-07-30 13:51 UTC, miguelpeixe commented on composer.lock
> +<<<<<<< HEAD
A pending conflict resolution got its way in a commit. The lock file is currently broken:

```

  "./composer.lock" does not contain valid JSON
  Parse error on line 1:
  {<<<<<<< HEAD	"_read
  ^
  Expected one of: 'STRING', '}'
```

2024-07-30 15:38 UTC, dkoo commented on composer.lock
> +<<<<<<< HEAD
Whoops! Fixed in 868e96b4, thanks for catching!

2024-07-30 15:40 UTC, dkoo commented on package.json
> +	"scripts": {
To wrap up this thread, we've decided that `fix:js` and `format:js` should both be present for all repos, but that they do different things: `fix:js` runs ESLint autofixing (for code quality issues) whereas `format:js` runs Prettier formatting (which should only affect code style and not functionality). We're mainly concerned about`fix:js` working as the ESLint stuff is more important to our workflows, but in the future we could decide to formally update our code style to match WP's Prettier configs.

2024-07-30 19:18 UTC, miguelpeixe commented
I find it strange that when I build/watch I get a bunch of deprecation warnings, e.g.:

```
    ╷
51  │ ┌     &,
52  │ │     &:visited:not(:hover) {
53  │ │         background: #d33;
54  │ │         color: #fff;
55  │ │     }
    │ └─── nested rule
... │
58  │       margin-left: auto;
    │       ^^^^^^^^^^^^^^^^^ declaration
    ╵
    newspack-theme/sass/navigation/_menu-mobile-navigation.scss 58:2  @use
    newspack-theme/sass/navigation/_navigation.scss 15:1              @use
    newspack-theme/sass/style-base.scss 22:1                          @use
    newspack-joseph/sass/style.scss 3:1                               root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls
```

But those are not caught with `npm run lint`. Is that expected?

2024-07-30 19:48 UTC, dkoo commented
@miguelpeixe I think this is because the Theme repo uniquely uses `sass` as a direct dev dependency, whereas the other repos just use whatever peer dependency `@wordpress/scripts` (and before that, Calypso Build) uses. Looks like the peer dependency specifies `^1.35.2` whereas the direct dependency in Theme is now `^1.77.8`. Looks like the deprecation warning was [just introduced](https://sass-lang.com/documentation/breaking-changes/mixed-decls/#deprecating-the-old-way) in `1.77.7`, so the linters from `@wordpress/scripts` won't show it since they're running an older version.

If it's obtrusive, we can always [silence the warnings](https://sass-lang.com/documentation/js-api/interfaces/options/#silenceDeprecations) in our Theme config. I'm fairly certain SASS wouldn't introduce a breaking change like this in a minor version, so the risk would be low.

2024-08-02 17:44 UTC, miguelpeixe approved these changes

2024-08-02 20:32 UTC, merged